<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Arifmetik ammallar
import numpy as np
arr=np.arange(8).reshape(2,4)
arr1=np.arange(11,19).reshape(2,4)



In [4]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr1

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [6]:
arr+arr1 # arr ning elementlarini arr1 ning elementlariga mos ravishda qo'shadi

array([[11, 13, 15, 17],
       [19, 21, 23, 25]])

In [7]:
arr*arr1 # arr ning elementlarini arr1 ning elementlariga mos ravishda  ko'paytiradi


array([[  0,  12,  26,  42],
       [ 60,  80, 102, 126]])

In [8]:
arr/arr1 # arr ning elementlarini arr1 ning elementlariga mos ravishda bo'ladi


array([[0.        , 0.08333333, 0.15384615, 0.21428571],
       [0.26666667, 0.3125    , 0.35294118, 0.38888889]])

In [9]:
arr**arr1 # arr ning elementlarini arr1 ning elementlariga mos ravishda darajaga oshiradi

array([[               0,                1,             8192,
                 4782969],
       [      1073741824,     152587890625,   16926659444736,
        1628413597910449]])

In [11]:
arr**(1/2) # arr ning elementlarini  kvadrat ildizini hisoblaydi


array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [12]:
arr1**2 # arr1 ning0 elementlarini kvadratga oshiradi

array([[121, 144, 169, 196],
       [225, 256, 289, 324]])

In [16]:
# substract() funksiyasi ham ayirish amalini bajaradi bu funk. binary funksiya hisoblanadi
ayirish=np.subtract(arr,arr1)
ayirish

array([[-11, -11, -11, -11],
       [-11, -11, -11, -11]])

In [18]:
mo=np.mod(arr,arr1)
mo

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
exp_arr=np.exp(arr)
exp_arr

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]])

In [22]:
# qo'shish funksiyasi add()
plus=np.add(arr,arr1)
plus

array([[11, 13, 15, 17],
       [19, 21, 23, 25]])

In [23]:
# power() funk. ham arr ning elementlarini arr1 ning elementlariga mos ravishda darajaga oshiradi
daraja_o=np.power(arr,arr1)
daraja_o

array([[               0,                1,             8192,
                 4782969],
       [      1073741824,     152587890625,   16926659444736,
        1628413597910449]])

In [25]:
# multiply() funksiyasi arr*arr1 ga teng
kopaytir=np.multiply(arr,arr1)
kopaytir

array([[  0,  12,  26,  42],
       [ 60,  80, 102, 126]])