<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/array_o'qlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# amaliyot
import numpy as np
A=np.arange(8).reshape(4,2)
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
A.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
B=np.array([[[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]]])
B.T

array([[[0],
        [2],
        [4],
        [6]],

       [[1],
        [3],
        [5],
        [7]]])

In [ ]:
A.swapaxes(0,1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
np.dot(A, A.T)

array([[ 1,  3,  5,  7],
       [ 3, 13, 23, 33],
       [ 5, 23, 41, 59],
       [ 7, 33, 59, 85]])

In [ ]:
# arange funksiyasidan foydalangan xolda massiv (array) yaratib olamiz
import numpy as np
arr_son=np.arange(8)
arr_son


array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# yuqoridagi massivimizni reshape funksiyasidan foydalangan xolatda shape=(q,u) larini berib olamiz
arr_kl=arr_son.reshape(4,2) # o'zimizga kerakli natijani oldik
arr_kl

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:

# vertikal xolatda turgan arrayimizni gorizontal xolatga o'tkazamiz
arr_kl.T # Trasnpose metodidan foydalanamiz


array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
# swaping axes metodidan foydalanamiz
arr_kl.swapaxes(1,0)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
# dot() funksiyasidan foydalanamiz. Bu funksiya arraylarni ko'paytirish uchun ishlatiladi
np.dot(arr_kl, arr_kl.T) # ko'ribturganingizdek arraylarni ko'paytirib berdi


array([[ 1,  3,  5,  7],
       [ 3, 13, 23, 33],
       [ 5, 23, 41, 59],
       [ 7, 33, 59, 85]])

# TAKRORLASH

In [ ]:
# array yaratamiz: reshape(q,u) 
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Trasnsope metodidan foydalanamiz
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
# yuqorida ko'rishingiz mumkin arr ni vertikal xolatga o'tkazib oldik


In [ ]:
# arr massivimizni swaping axes metodidan foydalangan xolda pozitsiyasini ko'chiramiz
arr.swapaxes(0,1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
# ko'ribturganingizdek arrayning pozitsiyasini o'zgartirdik


In [ ]:
# arraylarni ko'paytirish
np.dot(arr, arr.T)

array([[ 30,  80],
       [ 80, 255]])