<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/BOOLEAN_INDEKSLASH_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BISMILLAH


In [ ]:
import numpy as np
talabalar_info=np.array(["Muhammadali","Sardor","Sanjar","Bobur","Doniyor","Sanjar","Dono"])
talabalar_info


array(['Muhammadali', 'Sardor', 'Sanjar', 'Bobur', 'Doniyor', 'Sanjar',
       'Dono'], dtype='<U11')

In [ ]:
baxolar=np.random.randint(3,5, size=(7,5))
baxolar

array([[3, 3, 3, 3, 4],
       [3, 4, 3, 3, 4],
       [4, 3, 4, 3, 3],
       [4, 3, 3, 4, 3],
       [4, 3, 4, 4, 4],
       [3, 3, 3, 3, 3],
       [3, 4, 4, 3, 4]])

In [ ]:

talabalar_info=="Sanjar"
baxolar[talabalar_info=="Sanjar"]

array([[4, 3, 4, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
baxolar[talabalar_info=="Dono"]

array([[3, 4, 4, 3, 4]])

In [ ]:
baxolar[talabalar_info=="Bobur"]

array([[4, 3, 3, 4, 3]])

In [ ]:
baxolar[talabalar_info=="Sardor", 3:]

array([[3, 4]])

In [ ]:
baxolar[talabalar_info=="Sanjar"]

array([[4, 3, 4, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
#  Sanjarning ma'lumotlaridan 2 va 3 ustunlarni olamiz
baxolar[talabalar_info=="Sanjar", 1:3] # ko'ribturganingizdek 2 va 3 ustunnlarni ajratib oldik


array([[3, 4],
       [3, 3]])

In [ ]:
# Sanjarni ma'lumotlaridan boshqa hamma ma'lumotlarni chiqarish
baxolar[talabalar_info!="Sanjar"]


array([[3, 3, 3, 3, 4],
       [3, 4, 3, 3, 4],
       [4, 3, 3, 4, 3],
       [4, 3, 4, 4, 4],
       [3, 4, 4, 3, 4]])

In [ ]:
# yuqoridagi kodni boshqacha usul bilan yozish ham mumkin (~) belgisini qo'llagan xolatda
baxolar[~(talabalar_info=="Sanjar")] # ko'ribturganingizdek yuqoridagi chiqqan qiymatlar bilan bir_hil


array([[3, 3, 3, 3, 4],
       [3, 4, 3, 3, 4],
       [4, 3, 3, 4, 3],
       [4, 3, 4, 4, 4],
       [3, 4, 4, 3, 4]])

In [ ]:
mask=(talabalar_info=="Sanjar") | (talabalar_info=="Dono") # bu yerda ( | ) belgisi or (yoki) degan ma'noni anglatadi
mask

array([False, False,  True, False, False,  True,  True])

In [ ]:
baxolar[mask] # biz Sanjar yoki Dono ning ma'lumotlarini chaqirib oldik "Lekin o'zim mantiqqa tushunmadim :)"

array([[4, 3, 4, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 4, 4, 3, 4]])

In [ ]:
# JAVOBNI SHU YERGA YOZING
def nd_array():
  arr_son=np.random.randint(1,9, size=(3,3))
  return arr_son
  
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """

In [ ]:
nd_array()

array([[6, 5, 5],
       [1, 4, 4],
       [3, 7, 7]])

In [11]:
# O'tgan darslarimizni takrorlab olamiz numpy kutubxonasini random funksiyalaridan foydalamiz
import numpy as np
arr_rand=np.random.rand(2,6) # bu metod 0 va 1 orasidagi sonlarni chaqiradi
 
arr_rand

array([[0.0577651 , 0.12685494, 0.89448703, 0.18231701, 0.57629904,
        0.98930808],
       [0.5327499 , 0.92420883, 0.41380321, 0.7734391 , 0.70338509,
        0.72430956]])

In [12]:
# randint
arr_randint=np.random.randint(12, size=(2,6)) # 0 dan 12 gacha bo'lgan sonlar orasidan ixtiyor sonlarni chaqirib olishini buyurdik
arr_randint

array([[ 2,  3,  4,  0,  3,  0],
       [ 6,  9,  5,  6,  9, 11]])

In [15]:
# rand
arr_rand=np.random.rand(4,6)

In [17]:
arr_rand

array([[0.93921781, 0.90995445, 0.28886465, 0.04401593, 0.10841833,
        0.77596269],
       [0.6273211 , 0.00507253, 0.12639085, 0.8142546 , 0.21038266,
        0.17204584],
       [0.9226841 , 0.74651675, 0.38240427, 0.59301151, 0.03588598,
        0.96734175],
       [0.61504732, 0.82497972, 0.01184647, 0.09309067, 0.41543495,
        0.268678  ]])

In [18]:
arr3d=np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]]) # 3 massiv (arrayni ichidan) 22, 23,25,26 sonlarini chaqirib olamiz
arr=arr3d[2]
arr_sl=arr[1:,1:]
arr_sl

array([[22, 23],
       [25, 26]])

In [ ]:
# ko'rganingizdek kerakli sonlarni chaqirib oldik. 


# E FEW MOMENTS LATER

In [19]:
# YUQORIDAGI MASSIVIMIZNI O'LCHAMINI TEKSHIRIB KO'RAMIZ
arr3d.ndim

3

In [20]:
# massivimiz 3 o'lchamli ekan


In [23]:
# massiv va list larning tezligini tekshirish
son=list(range(1000000))
son_array=np.arange(1000001)
%time for kl in range(100): [g*2 for g in son] # LIST
%time for kk in range(100): son_array*2 #MASSIV

CPU times: user 9.21 s, sys: 1.85 s, total: 11.1 s
Wall time: 11.1 s
CPU times: user 255 ms, sys: 13.8 ms, total: 268 ms
Wall time: 261 ms


In [24]:
 # E FEW MOMENTS LATER
 # ko'ribturganingizdek ancha tez ishlaydi

In [26]:
# int128  turdagi array yaratamiz
arr_son=np.array([45,23,65,32,4,1,2,32,3,2],dtype=np.int64)
arr_son

array([45, 23, 65, 32,  4,  1,  2, 32,  3,  2])

In [27]:
# yuqoridagi ko'dimizni tekshiramiz
arr_son.dtype  # int64 ekan

dtype('int64')

In [28]:
# yuqoridagi ko'dimizni float16 ga o'tkazamiz
arr_float=arr_son.astype(np.float16)

In [30]:
arr_float.dtype

dtype('float16')

In [ ]:
# ko'rishingiz mumkin int64 array float16 ga o'tdi
