<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/DF_indexlargacha_takrorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch



In [ ]:
# RUN qilishni CPU da GPU ga o'tkazish va tekshirish
torch.cuda.is_available()
# quyida ko'rishingiz mumkin gpu ga o'tgan

True

In [ ]:
# biz ishlayotgan blaknotda qanday fayllar bo'rligini tekshirish
! ls

data  sample_data


In [ ]:
# keling exel formatidagi jadvalni yuklab ochamiz
read_file=pd.read_excel("./data/Slovar.xlsx")
read_file

Анг.слова Произношенние           Перевод
0     pronоunce      пронаунс      произношение
1       mistake       misteyk            ошибка
2          band          bend       муз. Ргуппа
3  introduction   introdakshn      ознакомление
4      spelling       speling  сказать буквенно
5         note           nout           eslatma
6          from          from      dan qo'shim.
7      singular       singula            birlik
8        plural        plural           ko'plik
9          None          naun                ot

In [ ]:
# keling keraklisini ajratib olamiz
read_file.head(3)

Анг.слова Произношенние       Перевод
0  pronоunce      пронаунс  произношение
1    mistake       misteyk        ошибка
2       band          bend   муз. Ргуппа

In [ ]:
# agar .head() deb orgument bermasak 5 tasini chiqarib beradi
read_file.head()

Анг.слова Произношенние           Перевод
0     pronоunce      пронаунс      произношение
1       mistake       misteyk            ошибка
2          band          bend       муз. Ргуппа
3  introduction   introdakshn      ознакомление
4      spelling       speling  сказать буквенно

In [ ]:
# keling array yaratamiz
sonlar=list(range(5))
arr=np.array(sonlar)

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
# arr ni o'lchamini tekshirish
arr.ndim # 1 o'lchamli array

1

In [ ]:
# arr.elementklar sonini tekshirish
arr.size

5

In [ ]:
# arr ni turini tekshirish
arr.dtype

dtype('int64')

In [ ]:
#arr ni turini float16 ga o'tkazish
arr2=arr.astype(np.float16) 

In [ ]:
arr2 # quyida ko'rishingiz mumkin float16 ga o'tdi

array([0., 1., 2., 3., 4.], dtype=float16)

In [ ]:
# array yaratish 2 usul
arr3=np.array([1,3,5,32,55], dtype=np.float32)
arr3

array([ 1.,  3.,  5., 32., 55.], dtype=float32)

In [ ]:
# 1 dan iborat bo'lgan array yaratish
arr_one=np.ones(shape=(2,4)) # 1 dan iborat bo'lgan 2 qator va 4 ustundan iborat bo'lgan arr yarat dedik
arr_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# yuqoridagi arrni o'lchamini tekshirish
arr_one.ndim

2

In [ ]:
# qator va ustun sonini tekshirish
# yangi rand metodidan foydalangan holda arr yaratamiz
arr_rand=np.random.rand(3,4)
arr_rand


array([[0.87337238, 0.49385365, 0.44924367, 0.08888054],
       [0.00109944, 0.11059024, 0.38422052, 0.02963434],
       [0.34500701, 0.17936686, 0.6262816 , 0.262961  ]])

In [ ]:
arr_rand.shape # arrayimiz 3 qator va 4 ta ustundan iborat ekan


(3, 4)

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr3

array([ 1.,  3.,  5., 32., 55.], dtype=float32)

In [ ]:
# keling arr va arr3 larni ko'paytiramiz
arr*arr3 # bir_biriga mos elementlarni ko'paytirdik

array([  0.,   3.,  10.,  96., 220.])

In [ ]:
# keling arr va arr3 larni dot() metodi yordamida ko'paytiramiz
arr.dot(arr3)

329.0

In [ ]:
# arr va arr3 larni ayramiz
arr-arr3 

array([ -1.,  -2.,  -3., -29., -51.])

In [ ]:
# arr va arr3 larni  subtract metodi yordamida ayramiz
np.subtract(arr, arr3)

array([ -1.,  -2.,  -3., -29., -51.])

In [ ]:
# arr va arr3 larni multiply() yordamida ko'paytiramiz
np.multiply(arr,arr3)

array([  0.,   3.,  10.,  96., 220.])

In [ ]:
arr_randint=np.random.randint(1,7,size=(2,3))
arr_randint1=np.random.randint(7,14,size=(2,3))

In [ ]:
arr_randint

array([[4, 3, 2],
       [4, 1, 3]])

In [ ]:
arr_randint1

array([[12, 12, 13],
       [ 9,  7, 12]])

In [ ]:
# yuqoridagi arr larni qo'shamiz .add() metodi yordamida
np.add(arr_randint,arr_randint1) # arr larni hos elementlarini yig'indis


array([[16, 15, 15],
       [13,  8, 15]])

In [ ]:
# + bilan qo'shish
arr_randint+arr_randint1

array([[16, 15, 15],
       [13,  8, 15]])

In [ ]:
# .power() metodi ham bor bu metod arr1 ning elementlarni arr2 ning elementlarini daraja sifatida oshiriladi
np.power(arr_randint,arr_randint1)

array([[16777216,   531441,     8192],
       [  262144,        1,   531441]])

In [ ]:
# .sum() degan metod ham bor u arr ning elementlarini yig'indisini hisoblaydi
np.sum(arr_randint) # 1 usul

17

In [ ]:
arr_randint.sum() # 2 usul

17

In [ ]:
# .sqrt() bu metod arrni elementlarini kvadrat ildizini hisoblaydi
np.sqrt(arr_randint)

array([[2.        , 1.73205081, 1.41421356],
       [2.        , 1.        , 1.73205081]])

In [ ]:
# square() kvadrat ga oshiradi
np.square(arr_randint)

array([[16,  9,  4],
       [16,  1,  9]])

In [ ]:
# yangi manfiy va musbat qiymati bor arr yaratamiz
arr=np.random.randn(2,4)
arr

array([[-0.72841572,  0.65749811,  0.21613302, -1.09726906],
       [-0.1655519 , -0.4356503 , -0.29056123, -0.7227283 ]])

In [ ]:
# sign() degan metod bor bu metod manfiy qiymatlarni (-1), musbat(1) va 0 ni (0) qilib beradi
np.sign(arr) 

array([[-1.,  1.,  1., -1.],
       [-1., -1., -1., -1.]])

In [ ]:
# yangi arr yaratamiz va .modf() metodini qo'llaymiz
arr2=np.array([2.9,3.6,-4.1,2.5])
# modf() butun va o'nlik qismini ajratib beradi
onlik,butun=np.modf(arr2)

In [ ]:
onlik # quyida ko'rayotgan bo'lsangiz o'lik qismini ajratib berdi

array([ 0.9,  0.6, -0.1,  0.5])

In [ ]:
butun # butun qismi

array([ 2.,  3., -4.,  2.])

In [ ]:
# keling yangi arr yaratib max va fmax metodlarni ishlatamiz
arr4=np.random.randint(2,9,size=(2,4))
arr4

array([[8, 2, 6, 2],
       [3, 3, 4, 7]])

In [ ]:
np.max(arr4) # max qiymati bizlarga eng katta qiymatni chiqarib beradi.


8

In [ ]:
# bir narsaga e'tibor bering arr4 miz int turida turibti uni nan o'tkazish uchun floatga o'tkazib olamiz
arr5=arr4.astype(np.float16)
arr5

array([[8., 2., 6., 2.],
       [3., 3., 4., 7.]], dtype=float16)

In [ ]:
arr5[:1,:1]=np.NaN 
arr5

array([[nan,  2.,  6.,  2.],
       [ 3.,  3.,  4.,  7.]], dtype=float16)

In [ ]:
np.fmax(arr5,arr4) # fmax() bu method agar arrlarning birida nan qiymat mavjud bo'lsa ularni inobatga olmay katta sonni chiqarib beradi

array([[8., 2., 6., 2.],
       [3., 3., 4., 7.]])

In [ ]:
# keling arraylardan chetlashib kutubxonalarmizni versiyasini ko'ramiz
np.__version__

'1.21.6'

In [ ]:
pd.__version__

'1.3.5'

In [ ]:
torch.__version__

'1.12.1+cu113'

In [ ]:
# yana bir ajoyib metod bor .linspace()
arr6=np.linspace(5,10,8) # 5 dan 10 gacha sonlardan 8 ta ihtiyoriysini oladi
arr6

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [ ]:
# indexlash va kesish. keling yangi 1 da 10 gacha sonlar ro'yhatini shakillantiramiz va ularni qiymatini o'zgartiramiz
arr6=np.arange(1,10,1) # 1 da 10 gacha 1 qadam bilan
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# arr6 ni arr7 ga nushasini olamiz va arr7 ninig 3 dan 6 gacha qiymatini 0 qilib qo'yamiz
arr7=arr6[:]

In [ ]:
arr7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7[3:6]=0
arr7

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
# yuqorida ko'rishingiz mumkin qiymat o'zgardi keling endi arr6 ni ko'ramiz
arr6 # ahamiyat bergan bo'lsangiz arr6 ning qiyamti ham o'zgargan buning oldini olish uchun .copy() metodidan foydalanamiz

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
arr8=arr6[:].copy()

In [ ]:
arr8

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
arr8[7:]=3

In [ ]:
arr8

array([1, 2, 3, 0, 0, 0, 7, 3, 3])

In [ ]:
arr6

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
# yuqorida ko'rishingiz mumkin qiymatlar biz kutgandek

# ***********************************************************************


In [ ]:
arr3d=np.array([[[1,6,8],
        [2,6,5],
        [8,5,4]],
       
       [[5,4,1],
        [2,56,4],
        [45,1,2]],
       
       [[2,2,5],
        [5,4,2],
        [4,5,5]]])
arr3d # manashu arrayning ichidan 3 massivning 4,2,5,5 qiymatlarini ajratib olamiz
 

array([[[ 1,  6,  8],
        [ 2,  6,  5],
        [ 8,  5,  4]],

       [[ 5,  4,  1],
        [ 2, 56,  4],
        [45,  1,  2]],

       [[ 2,  2,  5],
        [ 5,  4,  2],
        [ 4,  5,  5]]])

In [ ]:
arr3d[2][1:,1:] # ko'rishingiz mumkin kerakli qiymatni ajratib oldik

array([[4, 2],
       [5, 5]])

In [ ]:
# boolean indexlashni ko'rib chiqamiz
avtolar=np.array(["carvet","camaroo","lambargini","ford","mustang"])
data=np.random.rand(5,3)

In [ ]:
avtolar

array(['carvet', 'camaroo', 'lambargini', 'ford', 'mustang'], dtype='<U10')

In [ ]:
data

array([[0.90754856, 0.11638991, 0.99284025],
       [0.14511791, 0.99693609, 0.6453973 ],
       [0.17260618, 0.71721058, 0.90643767],
       [0.98784452, 0.90897606, 0.87197622],
       [0.54090594, 0.01046075, 0.7973883 ]])

In [ ]:
# dataning birinchi ustuni carvetning infosi hisoblanadi
data[avtolar=="carvet"]


array([[0.90754856, 0.11638991, 0.99284025]])

In [ ]:
data[avtolar=="camaroo"]  # 2ustun camarooniki

array([[0.14511791, 0.99693609, 0.6453973 ]])

In [ ]:
# dataning ohirgi ustunini olasaham bo'ladi
data[avtolar=="ford",2:] # quyida ko'rishingiz mumkin 3 ustundan data oldi

array([[0.87197622]])

In [ ]:
# ikkita avtoni datasini ko'rish
two_avto=(avtolar=="lambargini") | (avtolar=="mustang")

In [ ]:
data[two_avto] # quyida ikkita avtoni datasi

array([[0.17260618, 0.71721058, 0.90643767],
       [0.54090594, 0.01046075, 0.7973883 ]])

#****************************************


In [ ]:
# o'qlar bilan ishlash
arr11=np.arange(1,13).reshape(3,4) # reshape metodi nechta qator va ustundan iborat bo'lishini bildiradi

In [ ]:
arr11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# arr11 ni o'qlarini o'zgartirib qo'yishimiz mumkin buning uchun 2 ta usl bor. 1).swapaxes() metodi. 2)Transpose( .T() ) metodi
# 1 usul
arr11.swapaxes(0,1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:

arr11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 2 usul
arr11.T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
# ikkita arrni ko'paytirish uchun mahsus .dot() metodi bor buning uchun o'qlar 2 hil bo'lshi kerak
arr11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr12=np.arange(11,23).reshape(3,4)
arr12

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [ ]:
arr12.dot(arr11.T) # biz bu yerda arr12 ni arr1ning Transposega ko'paytirdik

array([[130, 330, 530],
       [170, 434, 698],
       [210, 538, 866]])

In [ ]:
arr11.dot(arr12.T)

array([[130, 170, 210],
       [330, 434, 538],
       [530, 698, 866]])

In [ ]:
arr13=arr12.T

In [ ]:
np.dot(arr11,arr13)

array([[130, 170, 210],
       [330, 434, 538],
       [530, 698, 866]])

In [ ]:
# .isnan() funksiyasi arrda nan qiymat bor yoki yo'qlgini tekshiradi
arr21=np.random.rand(2,3)
arr21

array([[0.41254465, 0.12062507, 0.82599663],
       [0.06950267, 0.83335679, 0.42958308]])

In [ ]:
arr21[:1,:1]=np.NaN

In [ ]:
arr21 

array([[       nan, 0.12062507, 0.82599663],
       [0.06950267, 0.83335679, 0.42958308]])

In [ ]:
np.isnan(arr21) # quyida ko'rishingiz mumkin 1 chi elementni True dedi ya'ni 1 chi element nan qiymat

array([[ True, False, False],
       [False, False, False]])

In [ ]:
arr22=np.random.rand(2,3)
arr22

array([[0.62796304, 0.49699602, 0.51134828],
       [0.74719771, 0.7878134 , 0.42293769]])

In [ ]:
# .maximum() funksiyasi ham bor bu funksiya ikkita arraydan mos elementlarini solishtirib eng katta qiymatni ajratib oladi

np.maximum(arr21,arr22)

array([[       nan, 0.49699602, 0.82599663],
       [0.74719771, 0.83335679, 0.42958308]])

In [ ]:
# DataFrame yaratib uystida ishlash
import pandas as pd
data1={"Full_name":["Muhammadali Boboxonov","Farxodov Sunnat","Ziyamov Doniyor"],
       "Tel:":[935772368,977701770,954444444],
       'Address':["Sergeli-6","Sergeli-8","Chilonzor"]}
df=pd.DataFrame(data1)
df

Full_name       Tel:    Address
0  Muhammadali Boboxonov  935772368  Sergeli-6
1        Farxodov Sunnat  977701770  Sergeli-8
2        Ziyamov Doniyor  954444444  Chilonzor

In [ ]:
# df ni indexlarini o'zmizga qulay qilib olamiz
df.index=[1,2,3]

In [ ]:
df 

Full_name       Tel:    Address
1  Muhammadali Boboxonov  935772368  Sergeli-6
2        Farxodov Sunnat  977701770  Sergeli-8
3        Ziyamov Doniyor  954444444  Chilonzor

In [ ]:
# o'zimizga kerakli bo'lgan indexlarni ajratib olishimiz ham mumkin
df.reindex([1,2])

Full_name       Tel:    Address
1  Muhammadali Boboxonov  935772368  Sergeli-6
2        Farxodov Sunnat  977701770  Sergeli-8

In [ ]:
# o'zimizga kerakli bo'lgan ustunni ajartib olishimiz ham mumkin 
df.reindex(columns=["Full_name","Address"])

Full_name    Address
1  Muhammadali Boboxonov  Sergeli-6
2        Farxodov Sunnat  Sergeli-8
3        Ziyamov Doniyor  Chilonzor

In [ ]:
# df ni indexlarni chaqirib olamiz
indexlar=df.index

In [ ]:
indexlar

Int64Index([1, 2, 3], dtype='int64')

In [ ]:
# yangi index yaratib olamiz
new_ind=pd.Index([1,3,4])
new_ind

Int64Index([1, 3, 4], dtype='int64')

In [ ]:
# keling endi indexlani jamlaymiz .union() metodi bilan
indexlar.union(new_ind)



Int64Index([1, 2, 3, 4], dtype='int64')

In [ ]:
# new_ind va indexlarning farqini topamiz .difference() metodi bilan
indexlar.difference(new_ind)

Int64Index([2], dtype='int64')

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data={"Yil":[2010,2012,2014,2016,2018,2020,2022],
      "Aholi soni":[28.0,30.0,31.5,32.0,32.5,32.8,33.0],
      "YAIM":["1.2$","1.5 $","1.8$","2.3$","3.0$","3.5","2.5"]}
df=pd.DataFrame(data)

In [ ]:
df # quyidagi ko'dni indexlarini o'zgartiramiz 

Yil  Aholi soni   YAIM
0  2010        28.0   1.2$
1  2012        30.0  1.5 $
2  2014        31.5   1.8$
3  2016        32.0   2.3$
4  2018        32.5   3.0$
5  2020        32.8    3.5
6  2022        33.0    2.5

In [ ]:
df.index=[1,2,3,4,5,6,7]

In [ ]:
df

Yil  Aholi soni   YAIM
1  2010        28.0   1.2$
2  2012        30.0  1.5 $
3  2014        31.5   1.8$
4  2016        32.0   2.3$
5  2018        32.5   3.0$
6  2020        32.8    3.5
7  2022        33.0    2.5

In [ ]:
# ko'rishingiz mumkin kerakli natijani oldik
# endi keling .renindex() metodini ishlatamiz, bu metod kerakli indexlarni chaqirib oladi(ustunlar ham indexga kiradi)
df.reindex([1,2,3]) # quyida ko'rishingiz mumkin 1,2 va 3 qator datalari chiqib keldi

Yil  Aholi soni   YAIM
1  2010        28.0   1.2$
2  2012        30.0  1.5 $
3  2014        31.5   1.8$

In [ ]:
# ustunlarni ham ajratib olishimiz mumkin
df.reindex(columns=["Yil","Aholi soni"])


Yil  Aholi soni
1  2010        28.0
2  2012        30.0
3  2014        31.5
4  2016        32.0
5  2018        32.5
6  2020        32.8
7  2022        33.0

In [ ]:
# ustun va indexlarni keraklisini ajratib olishimiz ham mumkin
df.reindex([1,2,3,4,5],columns=("Yil","YAIM")) # quyida ko'rishingiz mumkin biz kutgan natijani oldik

Yil   YAIM
1  2010   1.2$
2  2012  1.5 $
3  2014   1.8$
4  2016   2.3$
5  2018   3.0$

In [ ]:
# bir narsaga e'tibor bersangiz biz tepada bir nechta o'zgartirishlar kiritdik lekin df o'zgargani yo'q
df

Yil  Aholi soni   YAIM
1  2010        28.0   1.2$
2  2012        30.0  1.5 $
3  2014        31.5   1.8$
4  2016        32.0   2.3$
5  2018        32.5   3.0$
6  2020        32.8    3.5
7  2022        33.0    2.5

In [ ]:
# df ni o'zgartirishni sal keyinroq ko'rib chiqamiz hozir esa keling df da kerakmas ma'lumotlarni o'chirib tashlaymiz
df.drop([1,2,3]) # ko'rishingiz mumkin 1,2 va 3 datalar o'chdi

Yil  Aholi soni  YAIM
4  2016        32.0  2.3$
5  2018        32.5  3.0$
6  2020        32.8   3.5
7  2022        33.0   2.5

In [ ]:
newind=pd.Index([1,11,41,5,7])
indexs=df.index

In [ ]:
newind

Int64Index([1, 11, 41, 5, 7], dtype='int64')

In [ ]:
indexs

Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [ ]:
# newind va indexs larning farqini .difference() orqali tekshiramiz
newind.difference(indexs) # farq 11 va 41 ekan


Int64Index([11, 41], dtype='int64')

In [ ]:
# .union metodini qo'llab ikkalasini elementlarini jamlaymiz
newind.union(indexs) # quyida ko'rishingiz mukin hamma elementlar jam bo'ldi


Int64Index([1, 2, 3, 4, 5, 6, 7, 11, 41], dtype='int64')

In [ ]:
# manatonic() metodi agar takrorlanuvchi qiymat bo'lsa True qaytaradi
column=df.columns

In [ ]:
column

Index(['Yil', 'Aholi soni', 'YAIM'], dtype='object')

In [ ]:
# is_manatonic () metodi berilgan qiymat bir hil yoki bir hil emasligni tekshiradi
column.is_manatonic()

AttributeError: ignored

In [ ]:
# .is_unique() harhilligini tekshiradi


In [ ]:
# unique metodi esa elementlarni birmartdan chiqarib beradi

In [ ]:
df

Yil  Aholi soni   YAIM
1  2010        28.0   1.2$
2  2012        30.0  1.5 $
3  2014        31.5   1.8$
4  2016        32.0   2.3$
5  2018        32.5   3.0$
6  2020        32.8    3.5
7  2022        33.0    2.5

In [ ]:
# jadvaldan kerakmas elementni o'chirish
df.drop(index=[1,2,3]) # ko'rishingiz mumkin 1,2 va 3 indexlar o'chdi

Yil  Aholi soni  YAIM
4  2016        32.0  2.3$
5  2018        32.5  3.0$
6  2020        32.8   3.5
7  2022        33.0   2.5

In [ ]:
# nafaqat qotorlarni balki ustunlarni ham tashlab yuborishimiz mumkin
df.drop("YAIM", axis=1) # YAIM ni tashlab yubordik


Yil  Aholi soni
1  2010        28.0
2  2012        30.0
3  2014        31.5
4  2016        32.0
5  2018        32.5
6  2020        32.8
7  2022        33.0

In [ ]:
#  df ga o'zgartirish kiritsak asosiysi o'zgarmayotgan edi keling shuni o'zgartirishni ko'ramiz inplace=True ni yozib
df.drop(index=[6,7],columns=["YAIM"],inplace=True) 

In [ ]:
df # ko'rishingiz mumkin asosiy df o'zgardi 

Yil  Aholi soni
1  2010        28.0
2  2012        30.0
3  2014        31.5
4  2016        32.0
5  2018        32.5

In [ ]:
# Serieslar bilan ishlash
sonlar=list(range(1,7))
obj=pd.Series(sonlar)

In [ ]:
obj # quyida ko'rishingiz mumkin 0 dan boshlangan qator index hisoblanadi shularni o'zimizga kerakli nomlarga o'zgartirishni ko'ramiz


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
obj.index=["bir","ikki","uch","to'rt","besh","olti"]

In [ ]:
obj # quyida ko'rishingiz mumkin indexlar o'zgardi


bir      1
ikki     2
uch      3
to'rt    4
besh     5
olti     6
dtype: int64

In [ ]:
# indexlarni ajratib olamiz
obj.index

Index(['bir', 'ikki', 'uch', 'to'rt', 'besh', 'olti'], dtype='object')

In [ ]:
# qiymatlarni ajratib olamiz
obj.values

array([1, 2, 3, 4, 5, 6])

In [ ]:
# objektni boshqacha usul bilan yaratsaham bo'ladi
en_uz={"apple":"olma",
       "car":"avtomobil",
       "union":"kino"}
obj2=pd.Series(en_uz)

In [ ]:
obj2 # natija biz kutgandek bo'ldi keling endi shularni ichidagi xatoni to'g'irlab qo'yamiz

apple         olma
car      avtomobil
union         kino
dtype: object

In [ ]:
obj2["union"]="ittifoq"

In [ ]:
obj2 # xato to'g'irlandi

apple         olma
car      avtomobil
union      ittifoq
dtype: object

In [ ]:
 obj # obj ni ustida turli arifmetik amallarni bajarishimiz mumkin
 

bir      1
ikki     2
uch      3
to'rt    4
besh     5
olti     6
dtype: int64

In [ ]:
np.sqrt(obj) # kvadrat ildizni hisoblash

bir      1.000000
ikki     1.414214
uch      1.732051
to'rt    2.000000
besh     2.236068
olti     2.449490
dtype: float64

In [ ]:
np.square(obj) # kvadratga oshirish


bir       1
ikki      4
uch       9
to'rt    16
besh     25
olti     36
dtype: int64

In [ ]:
obj3=obj.astype(np.float16)

In [ ]:
# modf() funksiyasini ishlatamiz
onlik, butun=np.modf(obj3)

In [ ]:
onlik

bir      0.0
ikki     0.0
uch      0.0
to'rt    0.0
besh     0.0
olti     0.0
dtype: float16

In [ ]:
butun

bir      1.0
ikki     2.0
uch      3.0
to'rt    4.0
besh     5.0
olti     6.0
dtype: float16

In [ ]:
# obj3 ning ichidan 4 dan katta sonlarni chaqirib olamiz
obj3[obj>4]

besh    5.0
olti    6.0
dtype: float16

In [ ]:
obj3.iloc[1] # obj3 dan haqiqiy indexsini berib chaqirib olish

2.0

In [ ]:
obj3 

bir      1.0
ikki     2.0
uch      3.0
to'rt    4.0
besh     5.0
olti     6.0
dtype: float16

In [ ]:
# obj3 ni indexlarini o'zimizga qulay xolatda tartiblasak bo'ladi
pd.Series(obj3,index=["besh","bir","to'rt","uch","olti","ikki"])# quyida ko'rishingiz mumkin biz kutgan natija

besh     5.0
bir      1.0
to'rt    4.0
uch      3.0
olti     6.0
ikki     2.0
dtype: float16

In [ ]:
# agar yuqorida kodni ichiga yo'q qiymatni bersak nan qaytaradi
obj4=pd.Series(obj3,index=["besh","bir","to'rt","uch","olti","ikki","sakkiz"])

In [ ]:
obj4


besh      5.0
bir       1.0
to'rt     4.0
uch       3.0
olti      6.0
ikki      2.0
sakkiz    NaN
dtype: float16

In [ ]:
# isnull() metodi nan qiymat bo'lsa True bo'lmasa False qaytaradi
obj4.isnull()  

besh      False
bir       False
to'rt     False
uch       False
olti      False
ikki      False
sakkiz     True
dtype: bool

In [ ]:
# notnull() nan qiymat bo'lsa False qaytaradi
obj4.notnull()

besh       True
bir        True
to'rt      True
uch        True
olti       True
ikki       True
sakkiz    False
dtype: bool

In [ ]:
arr=np.arange(1,7).reshape(2,3)

In [ ]:
arr2=arr.astype(np.float16)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[:1,:1]=np.NaN

In [ ]:
arr2

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float16)

In [ ]:
# arrayda isnan funksiyasi bor u funksiya arrayda nan qiymati bo'lsa True qaytaradi
np.isnan(arr2)

array([[ True, False, False],
       [False, False, False]])

In [ ]:
# fayllar bilan ishlash
# .save() funksiyasi bitta fayl qo'shadi 
names=["Odil","Shezod","Humoyun","Zilola"]
file1=np.save("names",names)


In [ ]:
# saqlangan faylni o'qish uchun np.load dan foydalanamiz
read1=np.load("names.npy")
read1

array(['Odil', 'Shezod', 'Humoyun', 'Zilola'], dtype='<U7')

In [ ]:
read1[1]

'Shezod'

In [ ]:
read1[0]

'Odil'

In [ ]:
# savez() ko'p faylni saqlaydi
yosh=[12,1,11,54,19]
manzil=["Beshqo'rg'on","Ipodrom","Yunusobo"]
files=np.savez("data",year=yosh,address=manzil) # o'zgaruvchiga yuklash kerak fayllarni

In [ ]:

read2=np.load("data.npz")

In [ ]:
read2['year'] # ko'rishingiz mumkin yosh chiqib keldi

array([12,  1, 11, 54, 19])

In [ ]:
read2['address']

array(["Beshqo'rg'on", 'Ipodrom', 'Yunusobo'], dtype='<U12')

In [ ]:
# savez_compressed() funksiyasi ham bor faylni siqadi
sonlar=list(range(1,25))
avtolar=['carvet','audi','honda','toyota']
file_c=np.savez_compressed("zip",a=sonlar,v=avtolar)

In [ ]:
read7=np.load('zip.npz')
read7['a']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
read7['v']

array(['carvet', 'audi', 'honda', 'toyota'], dtype='<U6')

In [1]:
import numpy as np
import pandas as pd


In [22]:
laptops={"ofice":{"lenovo":"NaN","asus":"asus","HP":"HP envy"},
         "gaming":{"lenovo":"lenovo lagion","asus":"NaN","HP":"HP omen"}}
df=pd.DataFrame(laptops)
df

ofice         gaming
lenovo      NaN  lenovo lagion
asus       asus            NaN
HP      HP envy        HP omen

In [23]:
# indexni ajratamiz
index=df.index

In [30]:
df.index.is_unique # demak dfning indexlari harhil shuning uchun True qaytardi

True

In [33]:
# df ga yana bitta lug'at qo'shamiz
laptops1={"ofice":{"dell":"dell xps 15","asus":"asus mmm"},
          "gaming":{"dell":"dell G15","asus":"asus TUF"}}
df.append(pd.DataFrame(laptops1))


ofice         gaming
lenovo          NaN  lenovo lagion
asus           asus            NaN
HP          HP envy        HP omen
dell    dell xps 15       dell G15
asus       asus mmm       asus TUF

In [38]:
df.index.unique() # quyida ko'rishingiz mumkin takrorlanmagan holda chiqdi


Index(['lenovo', 'asus', 'HP'], dtype='object')

In [40]:
df["ofice"] 

lenovo        NaN
asus         asus
HP        HP envy
Name: ofice, dtype: object

In [41]:
type(df["ofice"])

pandas.core.series.Series

In [42]:
df[["ofice"]]

ofice
lenovo      NaN
asus       asus
HP      HP envy

In [43]:
type(df[["ofice"]])

pandas.core.frame.DataFrame

In [44]:
df2=df[["ofice"]]

In [45]:
df2

ofice
lenovo      NaN
asus       asus
HP      HP envy

In [47]:
df2.drop(["lenovo"]) # quyida ko'rishingiz mumkin lenovo datasini tashlab yubordik lekin asl df2 o'zgarmagan

ofice
asus     asus
HP    HP envy

In [48]:
df2 

ofice
lenovo      NaN
asus       asus
HP      HP envy

In [50]:
# df dan kerakmas ustunlarni tashlab yuboramiz
df.drop(columns=["ofice"])

gaming
lenovo  lenovo lagion
asus              NaN
HP            HP omen

In [52]:
df # kelin reindex yordamida  kerakli datalarni ajratib olamiz

ofice         gaming
lenovo      NaN  lenovo lagion
asus       asus            NaN
HP      HP envy        HP omen

In [53]:
df.reindex(["lenovo"])

ofice         gaming
lenovo   NaN  lenovo lagion

In [55]:
df["lenovo":"HP"] # manashu tarzda chaqirib olasak ham bo'ladi

ofice         gaming
lenovo      NaN  lenovo lagion
asus       asus            NaN
HP      HP envy        HP omen

In [57]:
df[0:] # manashunday qilib ham chaqirib olsa bo'ladi

ofice         gaming
lenovo      NaN  lenovo lagion
asus       asus            NaN
HP      HP envy        HP omen