<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/indekslash_va_kesish_Amaliyot_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# array ni ideks bilan chaqirish
import numpy as np
arr_range=np.arange(10,100,10)
arr_range[2]

30

In [2]:
arr_range

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
arr_six=arr_range[4:6] # 4 va 6 orasidagi Ikki nuqta 4 dan 6 gacha bo'lgan qiymarlarni olishini buyuradi 6 dagi qiymat olinmaydi
arr_six[:]=0

In [11]:
# arr_six dagi qiymatlarni 0 ga tenglashtiramiz va arr_range ning qiymatini ko'ramiz
arr_six

array([0, 0])

In [13]:
arr_range # ko'ribturibsiz [4:6] qiyamtlar 0 ga teng bo'lib qoldi

array([10, 20, 30, 40,  0,  0, 70, 80, 90])

In [19]:

arr_range1=np.arange(10,100,10)
arr_range1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
# arr_range funksiyasi o'zgarmaydigan qilib nusha ko'chiramiz
arr_six1=arr_range1[4:6].copy()
arr_six1

array([50, 60])

In [20]:
arr_six[:]=0
arr_six

array([0, 0])

In [22]:
arr_range1 # ko'ribturganingizdak qiymatlarning hammasi joyida

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
# ikki o'lchamli massiv(array) yaratib olamiz
arr_2=np.array([[1,5,6],[5,6,9],[2,5,8]]) # 3 ga 3 ko'rishdagi massiv
arr_2
 

array([[1, 5, 6],
       [5, 6, 9],
       [2, 5, 8]])

In [24]:
arr_2[1,2]

9

In [26]:
arr_k=arr_2[2, 1:3]

In [27]:
arr_k

array([5, 8])

In [34]:
arr3d=np.array([[[1,6,8],
        [2,6,5],
        [8,5,4]],
       
       [[5,4,1],
        [2,56,4],
        [45,1,2]],
       
       [[2,2,5],
        [5,4,2],
        [4,5,5]]])
arr3d

array([[[ 1,  6,  8],
        [ 2,  6,  5],
        [ 8,  5,  4]],

       [[ 5,  4,  1],
        [ 2, 56,  4],
        [45,  1,  2]],

       [[ 2,  2,  5],
        [ 5,  4,  2],
        [ 4,  5,  5]]])

In [36]:
arr3d[0][1, 2]

5

In [37]:
arr3d[1][2, :]

array([45,  1,  2])

In [38]:
# takrorlash 
# GPU ni CPU dan qancha tez ishlashini tekshiramiz
import numpy as np
sonlis=list(range(1000000))
son_arr=np.arange(1000000)
%time for k in range(10): [l**2 for l in sonlis]
%time for s in range(10): son_arr**2

CPU times: user 2.03 s, sys: 89.7 ms, total: 2.12 s
Wall time: 2.22 s
CPU times: user 8.5 ms, sys: 0 ns, total: 8.5 ms
Wall time: 6.79 ms


In [39]:
# bularning farqini topish uchun list va array ning vaqtlarini bir-biriga bo'lamiz


In [1]:
# GPU ishga tushuramiz va tekshiramiz 
import torch 
torch.cuda.is_available()

True

In [2]:
# yuqorida ko'rishingiz mumkin True qiymat qaytardi demak GPU ishlayapti


In [6]:
# ikki o'lchamli massiv (array) yaratishni o'rganamiz
import numpy as np
arr_son=np.array([[1,2,3]]) # 2 o'lchamli massiv yaratildi endi buni tekshiramiz to'g'rmi yo'qmi.
arr_son.ndim # quyi tomonda 2 o'lchamdaligini ko'rsatdi demak to'g'ri



2

In [8]:
# arr_son  nechta elementdan iborat ekanini tekshiramiz
arr_son.size
# 3 ta elementdan iborat ekan

3

In [13]:
# ikki o'lchamli massiv (array) ning ichidan kerakli qiymatni chaqirib olamiz
arr_son[0][1] # 0 chi ro'yhat ichidagi 1 chi qiymatni chaqirib oldik



2

In [14]:
arr_son[0][:]


array([1, 2, 3])

In [16]:
# arrayni necha qator va ustundan iborat ekanini tekshirish
arr_son.shape # 1 ta qator  va 3 ustundan iborat ekan

(1, 3)

In [18]:
# 0 dan iborat bo'lgan massiv yaratishni o'raganamiz
zero_arr=np.zeros( shape=(4,6))
zero_arr 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
# yuqoridagi ko'dni qisqaroq yozamiz
zero_arr=np.zeros((4,6))
zero_arr 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
# 1 dan iborat bo'lgan array yaratamiz
arr_one=np.ones((5,9))
arr_one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# np kutubxonasini random funksiyalaridan foydalanamiz
arr_rand=np.random.rand(4,6) # 0 va 1 orasidan ixtiyoriy sonlarni chiqazib beradi
arr_rand

array([[0.53707074, 0.68381766, 0.92096446, 0.26810551, 0.89554881,
        0.1910573 ],
       [0.16267082, 0.79018731, 0.08274394, 0.41856024, 0.69995546,
        0.34587708],
       [0.77279142, 0.30605544, 0.33259665, 0.3460635 , 0.43489578,
        0.49036155],
       [0.96584321, 0.14752838, 0.70689121, 0.47205913, 0.05966343,
        0.72017541]])

In [27]:
arr_randn=np.random.randn(2,5)
arr_randn

array([[-0.90452749,  1.1075131 ,  1.27218213,  0.31465824,  1.63877556],
       [ 0.40315102, -2.40344071, -0.8376012 ,  0.77087099,  0.494693  ]])

In [37]:
import numpy as np
while True:
 arr_randint=np.random.randint(5, size=(2,4)) # 0 dan  5 gacha bo'lgan ixtiyoriy sonlarni chiqarib beradi
 print(arr_randint,end="")

Выходные данные были обрезаны до нескольких последних строк (5000).
 [4 1 1 1]][[2 3 2 1]
 [4 3 0 4]][[0 0 3 4]
 [4 0 2 4]][[1 4 2 0]
 [3 4 3 4]][[3 3 2 2]
 [0 0 4 2]][[0 4 0 4]
 [1 1 3 3]][[1 1 0 0]
 [2 3 3 4]][[2 3 4 0]
 [1 0 1 2]][[2 4 3 0]
 [4 1 1 1]][[2 2 1 2]
 [1 2 2 2]][[3 3 3 4]
 [1 0 1 0]][[4 4 2 3]
 [0 4 4 3]][[4 2 3 3]
 [4 3 0 2]][[1 3 3 3]
 [3 1 0 1]][[4 3 1 0]
 [0 3 0 3]][[0 2 1 1]
 [4 2 2 2]][[4 4 2 0]
 [0 4 3 3]][[3 2 3 2]
 [1 2 2 2]][[1 1 3 1]
 [3 2 1 0]][[1 0 3 3]
 [0 4 3 4]][[1 1 0 1]
 [0 3 1 1]][[0 0 2 3]
 [1 1 1 2]][[1 0 0 1]
 [2 0 4 3]][[2 2 3 1]
 [4 0 3 2]][[4 3 1 4]
 [2 0 1 3]][[1 1 1 4]
 [1 1 3 2]][[0 1 4 3]
 [0 1 0 0]][[4 3 1 4]
 [4 2 2 4]][[0 3 0 0]
 [1 0 2 0]][[1 0 1 2]
 [2 4 2 2]][[1 3 2 0]
 [0 3 3 3]][[2 2 4 2]
 [4 4 4 0]][[0 4 3 3]
 [0 2 3 3]][[4 1 3 2]
 [0 1 4 3]][[1 4 3 1]
 [0 2 4 1]][[0 2 1 2]
 [1 2 0 3]][[3 3 1 0]
 [0 4 1 4]][[1 4 0 2]
 [1 1 2 3]][[0 3 0 4]
 [4 0 0 0]][[0 0 0 1]
 [4 1 3 1]][[3 4 0 0]
 [0 0 0 0]][[1 3 4 4]
 [0 0 4 0]][[4 0 0 1]
 [2 3 0 

KeyboardInterrupt: ignored

In [38]:
# array larga harhil ma'lumot turini berib yaratamiz
arr_range=np.arange(1,50,2,dtype=np.int16)
arr_range

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49], dtype=int16)

In [39]:
# yuqoridagi int16 turidagi arrayni float64 ga o'tkazamiz
arr_float=arr_range.astype(np.float64)
arr_float

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49.])

In [41]:
# yuqoridagi arrayimizni turini aniqlaymiz
arr_float.dtype # ko'ribturganingizdek float64 turida

dtype('float64')

In [43]:
# arraylarni indekslash va kesish
# ikki o'chamli arraydan kerakli  qiymatni chiqarib olamiz

arr2d=np.array([[2,3,6],
       [3,2,5],
       [4,2,5]])
arr2d      

array([[2, 3, 6],
       [3, 2, 5],
       [4, 2, 5]])

In [46]:
arr2d[2,  :]

array([4, 2, 5])

In [48]:
# 3 o'lchamli massiv yaratamiz
arr3d=np.array([[[1,3,5],
                 [4,5,6],
                 [12,54,22]],
                
                [[45,85,56],
                 [55,88,99],
                 [4,2,0]],
                
                [[12,44,15],
                 [45,45,55],
                 [12,11,77]]])
arr3d

array([[[ 1,  3,  5],
        [ 4,  5,  6],
        [12, 54, 22]],

       [[45, 85, 56],
        [55, 88, 99],
        [ 4,  2,  0]],

       [[12, 44, 15],
        [45, 45, 55],
        [12, 11, 77]]])

In [49]:
# arr3d ning ichidagi xar bir 2 o'lchamli arrayni chaqirib olamiz
arr3d[0]

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [12, 54, 22]])

In [50]:
arr3d[1]

array([[45, 85, 56],
       [55, 88, 99],
       [ 4,  2,  0]])

In [51]:
arr3d[2]

array([[12, 44, 15],
       [45, 45, 55],
       [12, 11, 77]])

In [52]:
# 3 arrayning ichidan 77 ni chaqiramiz
arr3d[2][2,2]

77

In [53]:
# 2 arrayni ichidan 99 ni chaqiramiz
arr3d[1][1,2]

99

In [54]:
# 1 arrayni ichidan 12,54,22 qiymatlarini chaqiramiz
arr3d[0][2, :]

array([12, 54, 22])

# BULARNING HAMMASI TAKRORLASH UCHUN YOZILGAN