<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Ma'lumotlar_turi_takrorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# arraylarni yaratganimizda ularning ma'lumot turlari kiritishni o'rganamiz
import numpy as np
arr_1=np.array([1,3,3,5,6,3,48,45], dtype=np.float)
arr_1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 1.,  3.,  3.,  5.,  6.,  3., 48., 45.])

In [ ]:
arr_1


array([ 1.,  3.,  3.,  5.,  6.,  3., 48., 45.])

In [ ]:
# arrayimizni int16 formatga o'tkazamiz
arr_int16=np.array(arr_1, dtype=np.int16)

In [ ]:
arr_int16

array([ 1,  3,  3,  5,  6,  3, 48, 45], dtype=int16)

In [ ]:
# arr_1 ni turini ko'rish uchun np.dtype metodidan foydalanamiz
arr_1.dtype

dtype('float64')

In [ ]:
# yuqorida ko'rishingiz mumkin arr_1 massiv(array) ni ma'l. turini chiqardik

In [ ]:
# array (massiv) mizni int16 yuqoridagdan oson int16  ga o'tkazishni o'rganamiz
import numpy as np
int_arr=arr_1.astype(np.int16)

In [ ]:
arr_1.dtype

dtype('float64')

In [ ]:
# TAKRORLASH
# colab ni GPU o'tkazish
import torch
torch.cuda.is_available()

True

In [6]:
# kutubxonalarni ishga tushirish
import tensorflow as tf
import matplotlib.pyplot as plt
import keras
import pandas as pd
import sklearn
import numpy as np

In [ ]:
! ls

sample_data  tekshirish


In [ ]:
# fayl chaqirib olamiz
read_file=pd.read_excel("./tekshirish/info_talabalar.xlsx")
read_file

№                  F.I.O  Bosqich   Hulqi  oraliq %  yakuniy %
0    1          Husanov Bobur      2.0    a'lo      66.0       88.0
1    2  Boboxonov Muhammadali      2.0  yaxshi     100.0      100.0
2    3   Mirfayziyeva Muhlisa      2.0  yaxshi     100.0      100.0
3    4        Hazratov Sanjar      2.0  yaxshi     100.0      100.0
4    5         Ungalov Farxod      2.0    a'lo     100.0      100.0
5    6       Komilova Dilnoza      2.0    a'lo     100.0      100.0
6    7      Karimova Dilafruz      2.0    a'lo     100.0      100.0
7    8                    NaN      NaN     NaN       NaN        NaN
8    9                    NaN      NaN     NaN       NaN        NaN
9   10                    NaN      NaN     NaN       NaN        NaN
10  11                    NaN      NaN     NaN       NaN        NaN
11  12                    NaN      NaN     NaN       NaN        NaN
12  13                    NaN      NaN     NaN       NaN        NaN
13  14                    NaN      NaN     NaN       NaN        NaN
14  15                    NaN      NaN     NaN       NaN        NaN
15  16                    NaN      NaN     NaN       NaN        NaN
16  17                    NaN      NaN     NaN       NaN        NaN
17  18                    NaN      NaN     NaN       NaN        NaN

In [ ]:
#  boshidan 3 ta  info chiqaramiz
read_file.head(3)

№                  F.I.O  Bosqich   Hulqi  oraliq %  yakuniy %
0  1          Husanov Bobur      2.0    a'lo      66.0       88.0
1  2  Boboxonov Muhammadali      2.0  yaxshi     100.0      100.0
2  3   Mirfayziyeva Muhlisa      2.0  yaxshi     100.0      100.0

In [ ]:
# array yaratish


arr=np.array([45,12,565,4545,42,121,])
arr

array([  45,   12,  565, 4545,   42,  121])

In [7]:
# ma'lumotni array (massiv) ga o'tkazish
son=[1,75,3,6,45,2,6,3,5,52]
son_arr=np.array(son)
son_arr

array([ 1, 75,  3,  6, 45,  2,  6,  3,  5, 52])

In [8]:
# array ni  nechchi o'lchamda ekanini tekshirish
son_arr.ndim

1

In [9]:
# array elementlar sonini tekshirish
son_arr.size

10

In [10]:
# 1 raqamidan iborat bo'lgan  massiv yaratish
import numpy as np
one_arr=np.ones(shape=(2,3))
one_arr 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# 0 raqamidan iborat bo'lgan array 
zero_arr=np.zeros(shape=(2,9))
zero_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# zeros va ones arrayni qisqa yozish
one_arr1=np.ones((3,4))
one_arr1


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
zero_arr1=np.zeros((4,6))
zero_arr1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
# array (massiv) ni arange metodidan foydalangan xolatda yatatamiz
arr_range=np.arange(25)
arr_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
# numpy kutubxonasining random metodidan foydalangan xolatda array yaratamiz
arr_rand=np.random.randn(2,6)
arr_rand

array([[ 0.30677558, -0.23872756, -1.18802907,  1.37568634,  0.71231816,
         0.33639616],
       [-1.50326061,  0.7935717 , -0.04076261, -0.10371941, -0.73475187,
        -1.63273223]])

In [34]:
arr_rand=np.random.rand(4,12)

In [36]:
arr_rand

array([[0.1316037 , 0.07646889, 0.3484863 , 0.45906897, 0.09657219,
        0.49532774, 0.99243853, 0.44655632, 0.32540829, 0.3401144 ,
        0.08221217, 0.39130419],
       [0.46426763, 0.25759853, 0.8767904 , 0.76721192, 0.34905411,
        0.31667937, 0.03365479, 0.898661  , 0.09562229, 0.34529592,
        0.46141961, 0.44039199],
       [0.03704608, 0.49434167, 0.6766451 , 0.96892992, 0.30035966,
        0.94468853, 0.82239281, 0.9771247 , 0.06187421, 0.44045015,
        0.77520183, 0.61876149],
       [0.08016211, 0.14322958, 0.11397567, 0.17948974, 0.81177498,
        0.16498342, 0.94230541, 0.6257951 , 0.72069638, 0.86516832,
        0.05254259, 0.3199832 ]])

In [37]:
arr_randint=np.random.randint(45,size=(2,55))

In [39]:
arr_randint

array([[14,  6, 10, 19, 19, 18,  9, 17,  5, 30, 16, 33,  7, 27,  1, 13,
        43, 10, 11, 39, 41,  0,  4, 15, 13, 36, 13, 38, 28, 20, 26, 22,
        26, 28,  2, 17,  1, 37, 23,  3, 44, 34,  1, 22,  1, 11, 19, 33,
        41,  5, 39, 44,  5,  8, 43],
       [39, 44, 34,  9, 31, 37,  5, 19, 35,  8,  7, 22, 18,  2, 40,  0,
        31, 38,  3, 26, 36, 26, 23,  3,  5, 43,  0,  6, 24, 16, 24, 33,
        15, 40, 41,  9,  4, 39, 35, 17, 18, 44, 42, 31, 32, 13, 34, 17,
        25,  4, 33,  5, 26, 40, 10]])

In [47]:
# int ma'lumot turi bilan ishlash
int_list=[2,11,77,4]
int_l=np.array(int_list)


In [49]:
int_l.dtype # yuqoridagi array ni turini ko'rdik

dtype('int16')

In [52]:
# int ni float16 qiyamtga o'tkazamiz
float_l=int_l.astype(np.float16)

In [53]:
float_l

array([ 2.,  4., 68., 45.], dtype=float16)

In [2]:
# array yaratganimizda ularning turini ham ko'rsatib ketishimiz mumkin
import numpy as np
arr_son=np.array([2,44,54,12,12], dtype=np.int16)


In [3]:
arr_son

array([ 2, 44, 54, 12, 12], dtype=int16)