<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# where funksiyasidan foydalanamiz


In [ ]:
# where funksiyasi huddi if operatori kabi ishlaydi misol
import numpy as np
arr1=np.array([1,4,3])
arr2=np.array([4,5,6])


In [ ]:
arr1

array([1, 4, 3])

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
kl=np.array([True, False ,False])
rlt=np.where(kl,arr1,arr2) # kl o'zgaruvchining ichidagi True arr1 ning elementini oladi False arr2 dan oladi
rlt

array([1, 5, 6])

In [ ]:
randint=np.random.randint(-2,5, size=(3,3))
randint

array([[ 3,  2, -2],
       [ 1, -1,  4],
       [-2,  4,  0]])

In [ ]:
w_r=np.where(randint>0, True, False)  
w_r

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True, False]])

# Yurqoridagi ko'dni tahlil qilamiz:
## randint massivimizni ichida 0 dan katta qiymatlar bo'lsa True ga o'zgartir dedik 0 dan kichkina bo'lsa False ga o'zgartir dedik. 

In [ ]:
import numpy as np
r_arr=np.random.randn(4,6)
r_t=np.where(r_arr<0,-1,1)

In [ ]:
r_arr

array([[ 0.04422247, -0.93034687, -0.99889381, -0.33107405, -0.94070051,
        -0.63825143],
       [-0.93711351, -1.08271684,  2.44381578,  0.04161399,  2.00789394,
         0.18472985],
       [-1.16709066,  0.18666426, -1.79002934,  0.19546108,  0.23287342,
        -1.24445719],
       [-0.62635671, -0.35164446,  0.97261762,  0.93525662,  0.17982046,
        -0.36775354]])

In [ ]:
r_t

array([[ 1, -1, -1, -1, -1, -1],
       [-1, -1,  1,  1,  1,  1],
       [-1,  1, -1,  1,  1, -1],
       [-1, -1,  1,  1,  1, -1]])

In [ ]:
ran_om=np.random.randint(-5,5,  size=(4,4))
ran_om

array([[ 2,  0, -1,  0],
       [ 2,  1, -5, -5],
       [ 0, -4, -5,  1],
       [-5, -1, -3, -2]])

In [ ]:
r_l=np.where(ran_om<0, True, False)
r_l

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])