<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Matematik_va_statistik_ammalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# array yartib olamiz
import numpy as np
arr1=np.random.randn(4,4)
arr1

array([[-0.01163293, -0.14728249,  0.64370233,  0.88356334],
       [ 0.03083276, -1.21438126, -0.90150488, -1.25490996],
       [-0.07720635,  0.86074501, -0.1506852 ,  0.7064742 ],
       [ 0.97142506,  1.3170525 ,  0.06763139, -1.34468237]])

In [ ]:
# sum() bu funksiya barcha elementlar yig'indisini hisoblab beradi
np.sum(arr1) 

0.37914112667134825

In [ ]:
arr1.sum() # yuqoridagi ko'dni qisqa ko'rinishi

0.37914112667134825

In [ ]:
arr1.sum(axis=1) # quyidagi elementlarning 1 chisi arr1 ning 1 qatoridagi sonlar yig'inidisiga teng. 2 chisi arr1 ning 2 chi qatorining yig'indisiga teng

array([ 1.36835024, -3.33996334,  1.33932766,  1.01142657])

In [ ]:
arr1.sum(axis=0) # ustun bo'yicha yig'indi

array([ 0.91341853,  0.81613375, -0.34085636, -1.00955479])

In [ ]:
info=np.arange(8).reshape(2,4)
info

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# mean() metodi o'rta arifmetik qiymatni hisoblaydi
info.mean()

3.5

In [ ]:
np.mean(info)

3.5

In [ ]:
# qatorlar bo'yicha hisoblaymiz
np.mean(info, axis=1)

array([1.5, 5.5])

In [ ]:
# yuqoridagi ko'dni qisqasi
info.mean(axis=1)

array([1.5, 5.5])

In [ ]:
# ustunlar bo'yicha o'rta arifmetik
info.mean(axis=0)

array([2., 3., 4., 5.])

In [ ]:
np.mean(info,axis=0)

array([2., 3., 4., 5.])

In [ ]:
# cumsum() metodi == fibonachi sonlar 
info.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [ ]:
np.cumsum(info)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [ ]:
np.cumsum(info, axis=0) # ustunlar bo'yich

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10]])

In [ ]:
np.cumsum(info,axis=1)  # qatorlar bo'yicha

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

# Takrorlash

In [4]:
# cumsum() metodi == fibonachi
import numpy as np
arr=np.arange(6).reshape(2,3)
arr


array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15])

In [6]:
# cumsum() ustunlar bo'yicha
arr.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]])

In [7]:
# cumsum() qatorlar bo'yicha
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [8]:
# mean() o'rta arifmetik qiymatni topish 
arr.mean(
    
)

2.5

In [9]:
np.mean(arr)

2.5

In [10]:
# mean() ustunlar bo'yicha
arr.mean(axis=0)


array([1.5, 2.5, 3.5])

In [11]:
# mean() qatorlar bo'yicha
arr.mean(axis=1)


array([1., 4.])

In [12]:
arr.sum()

15

In [13]:
arr.sum(axis=0) # sum() ustunlar bo'yicha

array([3, 5, 7])

In [14]:
np.sum(arr,axis=1) # sum() qatorlar bo'yicha

array([ 3, 12])

In [15]:
arr2=np.random.randint(2,8, size=(2,3))
arr2

array([[7, 4, 3],
       [2, 4, 7]])

In [19]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
arr2

array([[7, 4, 3],
       [2, 4, 7]])

In [21]:
# ikkita massivni hos elementlarini ayrish metod orqali
minus=np.subtract(arr,arr2)
minus

array([[-7, -3, -1],
       [ 1,  0, -2]])

In [22]:
# ikkita massivni hos elementlarini oddiy ayrish
min=arr-arr2 

In [23]:
min

array([[-7, -3, -1],
       [ 1,  0, -2]])

In [24]:
# ikkita massivni hos elementlarini ko'paytirish multiply() 
kopaytma=np.multiply(arr,arr2)
kopaytma



array([[ 0,  4,  6],
       [ 6, 16, 35]])

In [26]:
# ikkita massivni hos elementlarini oddiy ko'paytirish
kop=arr*arr2
kop

array([[ 0,  4,  6],
       [ 6, 16, 35]])

In [28]:
# ikkita massivni hos elementlarini qo'shish add()
plus=np.add(arr,arr2)
plus

array([[ 7,  5,  5],
       [ 5,  8, 12]])

In [30]:
# ikkita massivni hos elementlarini qo'shish oddiy
sum=arr+arr2
sum

array([[ 7,  5,  5],
       [ 5,  8, 12]])

In [31]:
# ikkita massivni hos elementlarini darajaga ko'tarish power()
dar=np.power(arr,arr2)
dar

array([[    0,     1,     8],
       [    9,   256, 78125]])

In [33]:
# ikkita massivni hos elementlarini darajaga ko'tarish oddiy
dar_arr=arr**arr2
dar_arr

array([[    0,     1,     8],
       [    9,   256, 78125]])