<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/N_o'lchovli_massiv_takrorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Bismillah.")

Bismillah.


In [ ]:
import pandas as pd
import numpy  as np
import tensorflow as tf
import keras
import sklearn
import matplotlib.pyplot as plt


In [3]:
import pandas 
read_file=pandas.read_excel("./read_ex/info_talabalar.xlsx")

In [4]:
read_file

№                  F.I.O  Bosqich   Hulqi  oraliq %  yakuniy %
0    1          Husanov Bobur      2.0    a'lo      66.0       88.0
1    2  Boboxonov Muhammadali      2.0  yaxshi     100.0      100.0
2    3   Mirfayziyeva Muhlisa      2.0  yaxshi     100.0      100.0
3    4        Hazratov Sanjar      2.0  yaxshi     100.0      100.0
4    5         Ungalov Farxod      2.0    a'lo     100.0      100.0
5    6       Komilova Dilnoza      2.0    a'lo     100.0      100.0
6    7      Karimova Dilafruz      2.0    a'lo     100.0      100.0
7    8                    NaN      NaN     NaN       NaN        NaN
8    9                    NaN      NaN     NaN       NaN        NaN
9   10                    NaN      NaN     NaN       NaN        NaN
10  11                    NaN      NaN     NaN       NaN        NaN
11  12                    NaN      NaN     NaN       NaN        NaN
12  13                    NaN      NaN     NaN       NaN        NaN
13  14                    NaN      NaN     NaN       NaN        NaN
14  15                    NaN      NaN     NaN       NaN        NaN
15  16                    NaN      NaN     NaN       NaN        NaN
16  17                    NaN      NaN     NaN       NaN        NaN
17  18                    NaN      NaN     NaN       NaN        NaN

In [5]:
! ls


read_ex  sample_data


In [6]:
import torch
torch.cuda.is_available()

False

In [1]:
import torch
torch.cuda.is_available()

True

In [4]:
# listni arrayga o'tkazamiz
import numpy
son_list=list(range(5000))
son_array=numpy.array(son_list)

In [6]:
# list yoki array qaysi biri tez ishlaydi
%time for k in range(10): [kl**2 for kl in son_list]
%time for s in range(10): son_array**2

CPU times: user 13.2 ms, sys: 643 µs, total: 13.9 ms
Wall time: 16.5 ms
CPU times: user 1.95 ms, sys: 0 ns, total: 1.95 ms
Wall time: 1.64 ms


In [8]:
#ularning orasidagi farqni topamiz
16.5/1.64

10.060975609756099

In [9]:
# array listdan 10 marotaba tezroq ishladi

In [10]:
# 1 o'lchamli massiv(array) larni yaratishni o'rganamiz
import numpy as np
sonlar_1=[1,21,45,22,32]
arr0=np.array(sonlar_1)


In [14]:
# massivni nechchi o'lchamdaligini aniqlaymiz
arr0.ndim

1

In [12]:
# massivni nechta qato, ustundan iboratligini aniqlaymiz
arr0.shape

(5,)

In [15]:
# massivda nechta elementi borligini ko'ramiz
arr0.size


5

In [17]:
# 0 dan iborat bo'lgan massiv(array) larni yaratamiz
arr_0=np.zeros((4,3))

In [18]:
arr_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# tepadagi ko'dimizni quyidagicha yozishimiz mumkin
arr_1=np.zeros(shape=(5,2))

In [20]:
arr_1


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# 1 dan iborat bo'lgan massiv(array)ni yaratamiz
arr_one=np.ones(shape=(5,9))
arr_one


array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# yuqoridagi ko'dni quyidagi tartibda yozishimiz mumkin
arr_ones=np.ones((4,8))

In [23]:
arr_ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
#  sonlarni ketma-ket tartibda massiv(array) yaratamiz.
son_array=np.arange(45)
son_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [25]:
# numpy kutubxonasini random funksiyasi ishlatamiz
ran_array=np.random.randint(45, size=(2,100))
ran_array

array([[24, 12, 18, 33, 19, 22,  7, 19,  9, 16, 26, 22, 42, 22, 13, 25,
        30, 40, 31, 33,  5, 44, 14, 38,  9, 43, 34, 26, 33, 12, 11,  6,
        15,  4,  5, 36, 41,  5, 14,  6, 13, 29, 44, 12, 24, 16, 40, 23,
         4, 42, 33, 28, 29,  7, 31, 29,  7, 27,  7, 21, 43, 35,  3,  7,
        31, 17,  2, 32, 31, 17, 44, 38, 42, 25, 44, 36, 42, 15, 29,  2,
         3, 23, 22, 44,  0, 22,  5, 21, 28,  3, 42, 33, 33,  5, 42, 14,
        11,  2,  3, 36],
       [38, 35, 44, 35, 36, 12, 14,  4, 35, 38,  4,  3,  5, 13, 19, 19,
        29, 38, 42, 21,  4, 22, 39, 16, 19, 40, 35,  0, 32, 17, 29, 44,
         4, 11, 32,  8, 19,  0,  1,  3, 21, 17, 29, 22, 44,  4, 24, 30,
        22, 16,  8,  7, 39, 39,  6, 18, 22, 30,  7, 41,  0, 25, 23, 42,
         5, 25,  6, 39,  1, 33, 36, 33, 21, 28, 42, 21, 39, 15, 18, 26,
        31, 36,  6,  8, 13, 34, 42, 28, 44,  0, 40, 20,  6, 22, 13, 21,
        40,  1, 16, 36]])

In [26]:
randn_arr=np.random.randn(4,12)

In [27]:
randn_arr

array([[ 0.05405596,  0.08232516, -0.45884063,  0.54875438,  0.68629876,
        -0.29522789,  0.14956601, -0.71694712, -0.37161814,  0.65446263,
         1.51417352, -0.14396492],
       [-0.625012  , -0.80657455, -1.60087367,  0.42758443, -0.82578525,
         0.30138193,  1.07533632,  0.88036036,  1.12477332,  0.6167966 ,
         1.03253156, -0.0079389 ],
       [ 0.9999919 , -0.45613065,  0.08273149, -1.58544417, -1.13209192,
         0.29974216, -0.8618677 ,  0.85624603,  0.69568934, -0.12905118,
         0.28863194,  2.46280322],
       [-1.98170906,  0.25432713,  0.11433171, -0.5182722 , -0.57899897,
         1.796521  ,  0.89063986,  1.23636531,  2.35969512, -1.10049405,
         0.66006967, -0.12594016]])

In [30]:
rand_arr=np.random.rand(4,10) # 0 va 1 orasidagi sonlarni oladi

In [31]:
rand_arr


array([[0.33320282, 0.62384891, 0.38176889, 0.61759361, 0.36945359,
        0.86188393, 0.11972924, 0.57114011, 0.28362469, 0.07723421],
       [0.14417813, 0.85496199, 0.3807745 , 0.79682945, 0.94918117,
        0.18686788, 0.70002636, 0.52387051, 0.53070853, 0.44819293],
       [0.49821328, 0.41230087, 0.78639644, 0.35785816, 0.84983365,
        0.52586467, 0.04053799, 0.510596  , 0.45010341, 0.12682702],
       [0.56800058, 0.0172846 , 0.73629178, 0.25082852, 0.12023715,
        0.99578266, 0.89536924, 0.61130373, 0.17918532, 0.10603075]])

In [35]:
# massiv(array) mizni turini aniqlash uchun .dtype metodidan foydalanamiz
rand_arr.dtype


dtype('float64')

In [36]:
son_array.dtype



dtype('int64')

In [39]:
# arrayimizda nechta element qatnashganini len () funksiyasi orqali bilishimiz mumkin
len (son_array)

45

In [38]:
son_array.size

45

In [42]:
# massiv yaratganimizda arrayimizni float ko'rinishda yaratishimiz mumkin
int_son=[2,32,656,545,78]
float_son=np.array(int_son, dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


In [43]:
float_son

array([  2.,  32., 656., 545.,  78.])

In [45]:
float_son.dtype

dtype('float64')

In [47]:
# yuqorida ko'rishingiz mumkin butun sonlarni float shakliga o'tkazdik.


In [53]:
# numpy kutubxonasida yana bir ajoyib metod linspace
arr_lins=np.linspace(2,3,5) # bu metod 2 dan 3  sonlar orasidan 5 ta sonni oladi


In [54]:
arr_lins

array([2.  , 2.25, 2.5 , 2.75, 3.  ])