<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Numpy_Full_repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# array yaratamiz
ints=list(range(14))


In [ ]:
import numpy as np

In [ ]:
arr1=np.array(ints)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
# arr1 ni o'lchamini tekshiramiz
arr1.ndim

1

In [ ]:
# arr1 ni elementlar sonini tekshiramiz
arr1.size

14

In [ ]:
# arr1 ni reshape() metodi yordamida ikki o'lchamli array qilib olamiz
arr2= arr1.reshape(2,7)

In [ ]:
arr2.ndim # arr2 o'lchamini tekshiramiz


2

In [ ]:
# arr2 ning o'qlarini swapaxes() metodi yordamida o'zgartiramiz
arr2.swapaxes(0,1)

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13]])

In [ ]:
arr3=arr2.swapaxes(0,1)

In [ ]:
arr3

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13]])

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
# arr2 va arr3 ni (dot) metodi yoradmida ko'paytiramiz
arr2.dot(arr3)

array([[ 91, 238],
       [238, 728]])

In [ ]:
arr3.dot(arr2)

array([[ 49,  56,  63,  70,  77,  84,  91],
       [ 56,  65,  74,  83,  92, 101, 110],
       [ 63,  74,  85,  96, 107, 118, 129],
       [ 70,  83,  96, 109, 122, 135, 148],
       [ 77,  92, 107, 122, 137, 152, 167],
       [ 84, 101, 118, 135, 152, 169, 186],
       [ 91, 110, 129, 148, 167, 186, 205]])

In [ ]:
np.dot(arr2,arr3)

array([[ 91, 238],
       [238, 728]])

In [ ]:
np.dot(arr3,arr2) # yuqoridagi dot() ishlatilgan ko'dlar bilan birhil

array([[ 49,  56,  63,  70,  77,  84,  91],
       [ 56,  65,  74,  83,  92, 101, 110],
       [ 63,  74,  85,  96, 107, 118, 129],
       [ 70,  83,  96, 109, 122, 135, 148],
       [ 77,  92, 107, 122, 137, 152, 167],
       [ 84, 101, 118, 135, 152, 169, 186],
       [ 91, 110, 129, 148, 167, 186, 205]])

In [ ]:
# uch o'lchamli massivv yaratamiz va ichidan kerakli bo'lgan qiymatlarni chaqirib olamiz
arr3d=np.array([[[ 49,  56,  63,  70,  77,  84,  91],
       [ 56,  65,  74,  83,  92, 101, 110],
       [ 63,  74,  85,  96, 107, 118, 129],
       [ 70,  83,  96, 109, 122, 135, 148],
       [ 77,  92, 107, 122, 147, 152, 167],
       [ 84, 181, 18, 135, 152, 169, 186],
       [ 91, 210, 19, 48, 167, 186, 605]],
       
       [[ 49,  56,  63,  70,  77,  84,  91],
       [ 56,  23,  74,  83,  9, 101, 110],
       [ 63,  74,  8,  96, 107, 118, 129],
       [ 70,  83,  96, 109, 22, 135, 148],
       [ 77,  92, 154, 12, 137, 152, 167],
       [ 84, 101, 118, 15, 152, 169, 186],
       [ 91, 110, 129, 48, 167, 86, 205]],
       
       [[ 49,  56,  63,  70,  77,  84,  91],
       [ 56,  23,  74,  83,  9, 101, 110],
       [ 63,  774,  558,  96, 107, 178, 129],
       [ 79,  83,  96, 104, 22, 13, 148],
       [ 77,  952, 154, 128, 137, 152, 167],
       [ 88, 181, 118, 157, 12, 169, 186],
       [ 91, 110, 129, 48, 167, 86, 205]]
       ])
arr3d


array([[[ 49,  56,  63,  70,  77,  84,  91],
        [ 56,  65,  74,  83,  92, 101, 110],
        [ 63,  74,  85,  96, 107, 118, 129],
        [ 70,  83,  96, 109, 122, 135, 148],
        [ 77,  92, 107, 122, 147, 152, 167],
        [ 84, 181,  18, 135, 152, 169, 186],
        [ 91, 210,  19,  48, 167, 186, 605]],

       [[ 49,  56,  63,  70,  77,  84,  91],
        [ 56,  23,  74,  83,   9, 101, 110],
        [ 63,  74,   8,  96, 107, 118, 129],
        [ 70,  83,  96, 109,  22, 135, 148],
        [ 77,  92, 154,  12, 137, 152, 167],
        [ 84, 101, 118,  15, 152, 169, 186],
        [ 91, 110, 129,  48, 167,  86, 205]],

       [[ 49,  56,  63,  70,  77,  84,  91],
        [ 56,  23,  74,  83,   9, 101, 110],
        [ 63, 774, 558,  96, 107, 178, 129],
        [ 79,  83,  96, 104,  22,  13, 148],
        [ 77, 952, 154, 128, 137, 152, 167],
        [ 88, 181, 118, 157,  12, 169, 186],
        [ 91, 110, 129,  48, 167,  86, 205]]])

In [ ]:
arr3d.ndim

3

In [ ]:
# arr3d ning 2 index ni ichidan 152,169,167,86 qiymatlarini chaqirib olamiz
arr3d[1][5:,4:6]

array([[152, 169],
       [167,  86]])

In [ ]:
arr3

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13]])

In [ ]:
arr3.sum()# arr3 ning elementlarini yig'indisini hisobladik

91

In [ ]:
np.sqrt(arr3) # arr3 ning elemetnlarini kvadrat ildizini hisoblash

array([[0.        , 2.64575131],
       [1.        , 2.82842712],
       [1.41421356, 3.        ],
       [1.73205081, 3.16227766],
       [2.        , 3.31662479],
       [2.23606798, 3.46410162],
       [2.44948974, 3.60555128]])

In [ ]:
np.square(arr3) #arr3 ni kvadrat ildizga oshirish

array([[  0,  49],
       [  1,  64],
       [  4,  81],
       [  9, 100],
       [ 16, 121],
       [ 25, 144],
       [ 36, 169]])

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
arr2.dtype # arr2 ni ma'lumot turini ko'rdik

dtype('int64')

In [ ]:
arr2.astype(np.float32) # arr2 ni ma'lumot turini float32 ga o'tkazib qo'ydik

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12., 13.]], dtype=float32)

In [ ]:
arr4=np.random.rand(5)

In [ ]:
arr5=np.random.rand(5)

In [ ]:
arr4

array([0.01131533, 0.79546727, 0.48652065, 0.63992917, 0.4008454 ])

In [ ]:
arr5

array([0.66297346, 0.27622772, 0.92808022, 0.59593727, 0.44423829])

In [ ]:
# mantiqiy shart operatori where()
shart=np.array([True,True, False,False,False])
rezult=np.where(shart,arr4,arr5) # shartda True qiymatga arr4 dan element oladi False ga arr5 dan oladi
rezult  

array([0.01131533, 0.79546727, 0.92808022, 0.59593727, 0.44423829])

In [ ]:
# where funksiyasi huddi if/else kabi ishlayi. MENIMCHA
arr6=np.where(arr3<5, True, False)
arr6

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False]])

In [ ]:
# arr6 ni o'zgartirib True, False ning o'rniga boshqa qiymat bersak ham bo'ladi
arr7=np.where(arr3<5, "0", "+5")
arr7

array([['0', '+5'],
       ['0', '+5'],
       ['0', '+5'],
       ['0', '+5'],
       ['0', '+5'],
       ['+5', '+5'],
       ['+5', '+5']], dtype='<U2')

In [ ]:
# array yaratganda uning ma'lumot turin berish
array=np.array([12,54,76,12],dtype=np.int16)

In [ ]:
array

array([12, 54, 76, 12], dtype=int16)

In [ ]:
array.dtype

dtype('int16')

In [ ]:
# arrayni float64 ga o'tkazamiz
ar_float=array.astype(np.float64)

In [ ]:
ar_float.dtype

dtype('float64')

In [1]:
# 1 dan iborat array yaratish
import numpy as np
from pandas  import Series


In [4]:
arr_ones=np.ones((4,5))
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
arr_ones1=np.ones(shape=(2,4))
arr_ones1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# 0 dan iborat array(massiv) yaratish
arr_zero=np.zeros(shape=(3,6))
arr_zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
arr_zero1=np.zeros((2,3))
arr_zero1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr11=np.random.randint(9,16,size=(2,3))
arr11

array([[ 9, 12, 15],
       [12, 10, 14]])

In [16]:
arr12=np.random.randint(8,15,size=(2,3))
arr12


array([[ 9, 12, 12],
       [13, 12, 14]])

In [17]:
# arr11 va arr12 larga binary funksiyalarni qo'llaymiz
# fmax()
np.fmax(arr11,arr12)

array([[ 9, 12, 15],
       [13, 12, 14]])

In [18]:
# power() arr11 ni arr12 ning elementlarini darajasiga ko'taradi
np.power(arr11,arr12)

array([[        387420489,     8916100448256,   129746337890625],
       [  106993205379072,     1000000000000, 11112006825558016]])

In [29]:
arr12swp=arr12.swapaxes(1,0)


In [30]:
# dot() metodi ikkita arrayni bir-biriga ko'paytiradi
np.dot(arr11,arr12swp)

array([[405, 471],
       [396, 472]])

In [31]:
np.dot(arr12swp,arr11)

array([[237, 238, 317],
       [252, 264, 348],
       [276, 284, 376]])

In [32]:
arr11.dot(arr12swp)

array([[405, 471],
       [396, 472]])

In [33]:
arr12swp.dot(arr11)

array([[237, 238, 317],
       [252, 264, 348],
       [276, 284, 376]])

In [34]:
#subtract() arr12 arr11 dan ayriladi
np.subtract(arr12,arr11) 

array([[ 0,  0, -3],
       [ 1,  2,  0]])

In [35]:
# add() arr11 ni arr12 ga qo'shadi
np.add(arr11,arr12)

array([[18, 24, 27],
       [25, 22, 28]])

In [36]:
#multiply() array elementlarini ko'paytiradi
np.multiply(arr11,arr12)

array([[ 81, 144, 180],
       [156, 120, 196]])

In [37]:
# isnan()
np.isnan(arr12)

array([[False, False, False],
       [False, False, False]])

In [47]:
arr12.dtype

dtype('int64')

In [48]:
arr13=arr12.astype(np.float16)

In [49]:
arr13[1][:2]=np.NaN

In [50]:
arr13

array([[ 9., 12., 12.],
       [nan, nan, 14.]], dtype=float16)

In [53]:
np.isnan(arr13) # arr13 da qiymat mavjud bo'lmagan element bo'lsa True bo'lmasa False

array([[False, False, False],
       [ True,  True, False]])

In [56]:
np.sum(arr12)# arr12 ichidagi barcha elementlar yig'insini hisoblaydi

59

In [57]:
arr12.sum()

59

In [59]:
arr12.mean()# arr12 o'rta arifmetigini hisoblaydi

9.833333333333334

In [65]:
# Tartiblash (sorting)
arr15=np.random.randn(2,4)
arr15

array([[-0.77069724,  1.70455984,  0.34687727,  1.2313897 ],
       [ 2.54495782, -1.7908783 , -1.4636404 , -0.80055061]])

In [66]:
# asl arr15 ning qiymatini o'zgartirmasdan tartiblash
arr16=np.sort(arr15)
arr16

array([[-0.77069724,  0.34687727,  1.2313897 ,  1.70455984],
       [-1.7908783 , -1.4636404 , -0.80055061,  2.54495782]])

In [67]:
arr15

array([[-0.77069724,  1.70455984,  0.34687727,  1.2313897 ],
       [ 2.54495782, -1.7908783 , -1.4636404 , -0.80055061]])

In [68]:
# arr15 ustunlar bo'yicha tartiblash
np.sort(arr15,axis=0)

array([[-0.77069724, -1.7908783 , -1.4636404 , -0.80055061],
       [ 2.54495782,  1.70455984,  0.34687727,  1.2313897 ]])

In [69]:
# arr15 ustunlar bo'yicha teskari tartiblash
-np.sort(-arr15,axis=0)

array([[ 2.54495782,  1.70455984,  0.34687727,  1.2313897 ],
       [-0.77069724, -1.7908783 , -1.4636404 , -0.80055061]])

In [70]:
# arr15 qatorlar bo'yicha tartiblash
np.sort(arr15,axis=1)

array([[-0.77069724,  0.34687727,  1.2313897 ,  1.70455984],
       [-1.7908783 , -1.4636404 , -0.80055061,  2.54495782]])

In [71]:
# arr15 qatorlar bo'yicha teskari tartiblash
-np.sort(-arr15,axis=1)

array([[ 1.70455984,  1.2313897 ,  0.34687727, -0.77069724],
       [ 2.54495782, -0.80055061, -1.4636404 , -1.7908783 ]])

In [72]:
# arr15 ni tartiblab qo'yamiz
arr15.sort()

In [73]:
arr15

array([[-0.77069724,  0.34687727,  1.2313897 ,  1.70455984],
       [-1.7908783 , -1.4636404 , -0.80055061,  2.54495782]])

In [74]:
arr17=np.arange(5,11)
arr17

array([ 5,  6,  7,  8,  9, 10])

In [75]:
# cumsum ( ) metodi ==fibonachi
np.cumsum(arr17)

array([ 5, 11, 18, 26, 35, 45])

In [76]:
# cumprod() har bir elementni ketma-ket ko'paytirib boradi
np.cumprod(arr17)

array([     5,     30,    210,   1680,  15120, 151200])