<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Takrorlanmas_va_boshqa_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello Mukhammadali


In [ ]:
# arraylarni yaratib olamiz
import numpy as np
names=np.array(["Dilorom","Jasur","Hamdam","Doston","Hamdam","Jasur"])
ints=np.random.randint(6, size=(1,6))


In [ ]:
names

array(['Dilorom', 'Jasur', 'Hamdam', 'Doston', 'Hamdam', 'Jasur'],
      dtype='<U7')

In [ ]:
ints

array([[4, 1, 2, 5, 4, 5]])

In [ ]:
# unique() metodi takrorlangan elementlarni takrorlamasdan konsolga chiqaradi
x_arr=np.unique(names)
x_arr

array(['Dilorom', 'Doston', 'Hamdam', 'Jasur'], dtype='<U7')

In [ ]:
x_ints=np.unique(ints)
x_ints

array([1, 2, 4, 5])

In [ ]:
sonlar1=np.random.randint(6,size=(1,6))
sonlar2=np.random.randint(2,6,size=(1,4))


In [ ]:
sonlar1

array([[0, 5, 1, 4, 1, 0]])

In [ ]:
sonlar2

array([[5, 2, 5, 5]])

In [ ]:
# in1d metodini ishlatamiz agar ikkala arrayda bo'lsa True bo'lmasa False qiymat qaytaradi
np.in1d(sonlar1,sonlar2)


array([False,  True, False, False, False, False])

In [ ]:
names1=np.array(["Doniyor", "Akmal","Anora","Muhlisa","Shovkat"])
names2=np.array(["Muhlisa","Sanjar","Shoxruh","Doniyor","Akmal"])
# setdiff1d( ) ikkala arr da bo'lmagan elementni chaqirib oladi
np.setdiff1d(names1,names2)

array(['Anora', 'Shovkat'], dtype='<U7')

# Takrorlash oxirgi 2 ta mavzuni.

In [2]:
# array yaratib olamiz
import numpy as np 
arr1=np.random.rand(6)
arr1


array([0.84292126, 0.22902338, 0.1479223 , 0.39752895, 0.29729825,
       0.42273743])

In [9]:
# arr1 ni o'zgartirmagan xolda sort() metodidan foydalanib tartiblaymiz
arr_sort=np.sort(arr1) 
arr_sort

array([0.1479223 , 0.22902338, 0.29729825, 0.39752895, 0.42273743,
       0.84292126])

In [10]:
# arr1 ni o'zgartirmagan xolda sort() metodidan foydalanib teskari tartiblaymiz
arr_min=-np.sort(-arr1)
arr_min

array([0.84292126, 0.42273743, 0.39752895, 0.29729825, 0.22902338,
       0.1479223 ])

In [12]:
# arr1 ni tartiblaymiz
arr1.sort()
arr1

array([0.1479223 , 0.22902338, 0.29729825, 0.39752895, 0.42273743,
       0.84292126])

In [13]:
# arr1 ni teskari tartiblaymiz
-np.sort(-arr1)

array([0.84292126, 0.42273743, 0.39752895, 0.29729825, 0.22902338,
       0.1479223 ])

In [15]:
arr2d=np.random.rand(3,5)
arr2d

array([[0.83440836, 0.17060589, 0.57383426, 0.56019333, 0.84455191],
       [0.20901283, 0.08247768, 0.82122987, 0.51799855, 0.97164651],
       [0.02954106, 0.88109677, 0.43636578, 0.38557462, 0.96661722]])

In [16]:
# arr2d  ustunlar bo'yicha tartiblaymiz
arr_us=np.sort(arr2d,axis=0)
arr_us

array([[0.02954106, 0.08247768, 0.43636578, 0.38557462, 0.84455191],
       [0.20901283, 0.17060589, 0.57383426, 0.51799855, 0.96661722],
       [0.83440836, 0.88109677, 0.82122987, 0.56019333, 0.97164651]])

In [18]:
# arr2d ustunlar bo'yicha teskari tartiblaymiz
arr_t=-np.sort(-arr2d,axis=0)
arr_t  # bu metod pythonda arr_t.sort(reverse=True) shaklida yoziladi


array([[0.83440836, 0.88109677, 0.82122987, 0.56019333, 0.97164651],
       [0.20901283, 0.17060589, 0.57383426, 0.51799855, 0.96661722],
       [0.02954106, 0.08247768, 0.43636578, 0.38557462, 0.84455191]])

In [19]:
# arr2d  qatorlar bo'yicha tartiblaymiz
arr_q=np.sort(arr2d,axis=1)
arr_q

array([[0.17060589, 0.56019333, 0.57383426, 0.83440836, 0.84455191],
       [0.08247768, 0.20901283, 0.51799855, 0.82122987, 0.97164651],
       [0.02954106, 0.38557462, 0.43636578, 0.88109677, 0.96661722]])

In [20]:
## arr2d  ustunlar bo'yicha teskari tartiblaymiz
arr_t=-np.sort(-arr2d,axis=1)
arr_t

array([[0.84455191, 0.83440836, 0.57383426, 0.56019333, 0.17060589],
       [0.97164651, 0.82122987, 0.51799855, 0.20901283, 0.08247768],
       [0.96661722, 0.88109677, 0.43636578, 0.38557462, 0.02954106]])

In [21]:
# unique() metodi set() metodi bilan birhil ishlidi
arr_son=np.random.randint(6,size=(1,6))
arr_son


array([[5, 5, 2, 4, 3, 0]])

In [22]:
np.unique(arr_son)

array([0, 2, 3, 4, 5])

In [24]:
names1=np.array(["Sanjar","Anora","Sojida","Gulsanam","Anora","Saida","Sojida"])
np.unique(names1)

array(['Anora', 'Gulsanam', 'Saida', 'Sanjar', 'Sojida'], dtype='<U8')

In [25]:
# in1d() ikkita arr ni solishtiradi agar ikkila arr da bir hil element bo'lsa True bo'lmasa False qaytaradi
names2=np.array(["Sanjar","Islom","Temur","Sojida"])
np.in1d(names1,names2)

array([ True, False,  True, False, False, False,  True])

In [26]:
# setdiff1d() ikkita arr ni solishtiradi agar ikkila arr da bir hil element bo'lmasa o'shani oladi
np.setdiff1d(names1,names2)

array(['Anora', 'Gulsanam', 'Saida'], dtype='<U8')