<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Tartiblash_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""Hello Mukhammadali"""


'Hello Mukhammadali'

In [2]:
import numpy as np

In [17]:
# arr yaratib olamiz
arr1=np.random.rand(5)
arr1

array([0.21199046, 0.78625323, 0.63535055, 0.29797331, 0.55609144])

In [21]:
sl=np.sort(arr1).copy() # arr1 ni ketmaket qilib tartiblaymiz asl nusxasini saqlagan xolda

sl

array([0.21199046, 0.29797331, 0.55609144, 0.63535055, 0.78625323])

In [22]:
arr1

array([0.21199046, 0.78625323, 0.63535055, 0.29797331, 0.55609144])

In [24]:
rev_arr=-np.sort(-arr1)
rev_arr

array([0.78625323, 0.63535055, 0.55609144, 0.29797331, 0.21199046])

In [26]:
arr1.sort()
arr1

array([0.21199046, 0.29797331, 0.55609144, 0.63535055, 0.78625323])

In [27]:
# ikki o'lchamli massiv yaratamiz
arr2d=np.random.randn(2,4)
arr2d

array([[ 0.84640578,  1.48338007,  1.40902446, -1.18437547],
       [ 0.3567256 , -1.7599033 ,  1.3633485 ,  0.48181144]])

In [29]:
# ustun bo'yicha tartiblaymiz
ust_arr=np.sort(arr2d, axis=0)
ust_arr

array([[ 0.3567256 , -1.7599033 ,  1.3633485 , -1.18437547],
       [ 0.84640578,  1.48338007,  1.40902446,  0.48181144]])

In [30]:
# ustun bo'yicha teskari tartiblaymiz
u_t_arr=-np.sort(-arr2d,axis=0)
u_t_arr

array([[ 0.84640578,  1.48338007,  1.40902446,  0.48181144],
       [ 0.3567256 , -1.7599033 ,  1.3633485 , -1.18437547]])

In [31]:
# qatorlar bo'yicha tartiblaymiz
qat_arr=np.sort(arr2d, axis=1)
qat_arr

array([[-1.18437547,  0.84640578,  1.40902446,  1.48338007],
       [-1.7599033 ,  0.3567256 ,  0.48181144,  1.3633485 ]])

In [32]:
# qatorlar bo'yicha teskari tartiblaymiz
q_t_arr=-np.sort(-arr2d, axis=1)
q_t_arr

array([[ 1.48338007,  1.40902446,  0.84640578, -1.18437547],
       [ 1.3633485 ,  0.48181144,  0.3567256 , -1.7599033 ]])

# MUSTAQIL TAKRORLASH

In [36]:
arr2=np.random.randint(20,29,size=(2,4))
arr2

array([[23, 21, 24, 21],
       [23, 28, 26, 22]])

In [39]:

# arr2 o'zgartirish kiritmay tartiblash
klone_arr=np.sort(arr2)
klone_arr

array([[21, 21, 23, 24],
       [22, 23, 26, 28]])

In [40]:
# arr2 tartiblash 
arr2

array([[23, 21, 24, 21],
       [23, 28, 26, 22]])

In [41]:
# arr2 ni  tartiblash
arr2.sort()
arr2

array([[21, 21, 23, 24],
       [22, 23, 26, 28]])

In [42]:
np.sort(arr2)

array([[21, 21, 23, 24],
       [22, 23, 26, 28]])

In [44]:
arr3=np.random.randn(6).reshape(2,3) #(2,3) massiv yaratamiz
arr3

array([[-0.00335104,  0.49256333, -0.48821554],
       [-0.48811672,  1.67547443, -1.43139467]])

In [45]:
# arr3 ustunlar bo'yicha tartiblash
arr3_u=np.sort(arr3,axis=0)
arr3_u

array([[-0.48811672,  0.49256333, -1.43139467],
       [-0.00335104,  1.67547443, -0.48821554]])

In [46]:
# arr3 ustunlar bo'yicha teskari tartiblash
arr_t=-np.sort(-arr3,axis=0)
arr_t

array([[-0.00335104,  1.67547443, -0.48821554],
       [-0.48811672,  0.49256333, -1.43139467]])

In [47]:
# arr3 ni qatrolar bo'yicha tartiblash
arr_q=np.sort(arr3,axis=1)
arr_q

array([[-0.48821554, -0.00335104,  0.49256333],
       [-1.43139467, -0.48811672,  1.67547443]])

In [48]:
# arr3 ni qatrolar bo'yicha teskari tartiblash
arr3_t=-np.sort(-arr3,axis=1)
arr3_t

array([[ 0.49256333, -0.00335104, -0.48821554],
       [ 1.67547443, -0.48811672, -1.43139467]])

In [49]:
! ls

sample_data


In [51]:
import pandas 
read_f=pandas.read_excel("./INFO/INFO.xlsx")
read_f.head(3)

№      РАЙОН                  Ф.И.О
0  1   ЮНУСОБОД          ХУСАНОВ БОБУР
1  2  СЕРГЕЛИ-6  БОБОХОНОВ МУХАММАДАЛИ
2  3  СЕРГЕЛИ-8        ФАРХОДОВ СУННАТ