<a href="https://colab.research.google.com/github/MUHAMMADALIBOBOKHON2003/mening_darslarim/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UNARY (faqat bitta element qabul qiluchi) funksiyalar.

In [ ]:
# sqrt() funksiyasi. Kvadrat ildiz hisoblaydi
import numpy as np 
arr1=np.arange(8)
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

# square() funksiyasi berilgan elementni kvadrat ildizga oshiradi
 

In [ ]:
np.square(arr1) 

array([ 0,  1,  4,  9, 16, 25, 36, 49])

# exp() funksiya berilgan qiymatni  exponentini qaytaradi


In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

# log() funksiyasi logorifmni hisoblaydi (loge)


In [ ]:
np.log(arr1[1:]) # 0 dan tashqari barcha elementlarni logosini hisoblab beradi


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

# modf() bu funksiya haqiqiy sonni butun va o'nlik qismini ajratib beradi
 

In [ ]:
arr1=np.random.randn(5)

In [ ]:
arr1

array([-0.82407195,  1.18970309, -0.05733944, -0.63652807, -0.59063345])

In [ ]:
qoldiq, butun=np.modf(arr1)

In [ ]:
print(butun)
print(qoldiq)

[-0.  1. -0. -0. -0.]
[-0.82407195  0.18970309 -0.05733944 -0.63652807 -0.59063345]


In [ ]:
# bu funksiya nuqtadan oldin qanday son turgan bo'lsa shuni butun deb qabul qilar ekan


# sign() bu funksiya agar berilgan qiymat musbat bo'lsa 1 ni manfiy bo'lsa -1 ni qaytaradi

In [ ]:
arr1

array([-0.82407195,  1.18970309, -0.05733944, -0.63652807, -0.59063345])

In [ ]:
np.sign(arr1)

array([-1.,  1., -1., -1., -1.])

In [ ]:
# yuqoridagi natijalarni solishtirishingiz mumkin

# isnan() bu funksiya array da NaN element bo'lsa True qaytaradi bo'lmasa False

In [ ]:
# isnan() tekshirib ko'ramiz
np.isnan(arr1) # quyida ko'rishingiz mumkin NaN yo'q demak hammasi False qaytdi

array([False, False, False, False, False])

In [ ]:
arr1[2]=np.NaN # arr1 ning 2 elementini NaN ga o'tkazdik



In [ ]:
np.isnan(arr1) # quyida ko'rishingiz mumkin 2 qiymatni True qaytardi

array([False, False,  True, False, False])

# binary funksiyalar (ikkita element qabul qiluvchi funksiya)

In [ ]:
# add funksiaysi massivlarni hos ravishda qo'shuvchi funksiya

import numpy as np
arr1=np.random.randn(5)
arr2=np.random.randn(5)
print(arr1)
print(arr2)

[ 1.39292735 -0.58897938 -0.59216083 -0.13221513  0.7709612 ]
[-0.4964056  -1.0911137   1.21537128 -0.14411794  0.46662775]


In [ ]:
np.add(arr1, arr2) # arr1 ni arr2 ga qo'shdi

array([ 0.89652175, -1.68009307,  0.62321045, -0.27633307,  1.23758895])

In [ ]:
sa= arr1+arr2 # <-mashi kodham yuqoridagi kodning qiymati bilan teng.

sa

array([ 0.89652175, -1.68009307,  0.62321045, -0.27633307,  1.23758895])

# multiply() ikkita massivning mos elementlari bir biriga 

In [ ]:
np.multiply(arr1, arr2) 

array([-0.69145694,  0.64264346, -0.71969527,  0.01905457,  0.35975189])

# maximum() bu funksiya 2 ta arrayning ichidagi elementlarni kattasini ajratib oladi

In [ ]:
arr1

array([ 1.39292735, -0.58897938, -0.59216083, -0.13221513,  0.7709612 ])

In [ ]:
arr2

array([-0.4964056 , -1.0911137 ,  1.21537128, -0.14411794,  0.46662775])

In [ ]:
np.maximum(arr1,arr2)

array([ 1.39292735, -0.58897938,  1.21537128, -0.13221513,  0.7709612 ])

In [ ]:
# yuqoridagi qiymatlarni ko'rib chiqing tashlab qo'ying

# UNIVERSAL FUNKSIYAGACHA O'TILGAN MAVZULARNI TAKRORLIMIZ


In [ ]:
# Testin qilishni  GPU ga  o'tkazamiz va ishlayotganini tekshiramiz
import torch
torch.cuda.is_available() # True qiymat qaytardi


True

# arraylarni yaratishni o'rganamiz

In [ ]:
sonlar_list=list(range(10))
sonlar_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import numpy as np
son_arr=np.array(sonlar_list)
son_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

# yuqorida ko'rishingiz mumkin listdan array (massiv) ga o'tkazib oldik


In [ ]:
# massiv va list ning hisoblash tezligini ko'ramiz
son_list=list(range(10000000))
son_arr=np.array(son_list)
%time for marta in range(10): [tt*2 for tt in sonlar_list]
%time for marta in range(10): son_arr*2

CPU times: user 16 µs, sys: 0 ns, total: 16 µs
Wall time: 18.6 µs
CPU times: user 222 ms, sys: 13.6 ms, total: 236 ms
Wall time: 235 ms


In [ ]:
# arrayning o'lchamini tekshirish uchun .ndim metodidan foydalanamiz
arrd=np.array([1,3,132,15,1321,321,32])
arrd.ndim

1

In [ ]:
# ikki o'lchamli massiv (array) yaratish
arr1=np.array([[1,2,3,3,4],[5,4,4,2,5]])
arr1

array([[1, 2, 3, 3, 4],
       [5, 4, 4, 2, 5]])

In [ ]:
arr1.ndim

2

In [ ]:
# yuqorida 2 o'lchamlik deb chiqardi


In [ ]:
# arrayni nechta qator va ustundan iborat ekanini tekshirish
arr1.shape  # 2 ta qator va 5 ustundan iborat ekan

(2, 5)

In [ ]:
# 0 dan iborat bo'lgan array yaratish
arr0=np.zeros(shape=(4,4)) # 4 ta qator va 4ta ustundan iborat bo'lsin dedik
arr0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 1 dan iborat bo'lgan array yaratish
arr_one=np.ones(shape=(2,3)) # 2 ta qator va 3 ta ustundan iborat bo'lsin dedik
arr_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# yuqoridagi ko'dni qisqaroq yozsak ham bo'ladi 
arr_one=np.ones((2,3))
arr_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#numpy kutubxonasining  random funksiyasiyasidan foydalamiz
arr_randn=np.random.randn(6) # 6 ta ixtiyor sonni oladi
arr_randn

array([ 0.92481536,  0.7819918 , -1.96372276, -0.4749119 ,  1.07338907,
        0.44538348])

In [ ]:
arr_rand=np.random.rand(2,6) # 2 ta qator va 6 ta ustundan iborat bo'lgan ixtiyoriy sonlarni chiqaradi
arr_rand

array([[0.77980924, 0.90485936, 0.11027746, 0.57350681, 0.65426812,
        0.10581611],
       [0.91236175, 0.77694032, 0.15051163, 0.16276933, 0.8102417 ,
        0.12588564]])

In [ ]:
arr_randint=np.random.randint(10,size=(6,6)) # maximum 10 gacha bo'lgan sonlardan iborat 6 qatot va 6 ustundan iborat bo'lgan array yaratish
arr_randint

array([[1, 5, 1, 6, 6, 7],
       [7, 1, 9, 0, 8, 2],
       [8, 9, 8, 3, 1, 9],
       [7, 4, 1, 0, 4, 6],
       [1, 6, 1, 0, 1, 0],
       [4, 4, 9, 7, 2, 5]])

In [ ]:
 # arrayni elementlar sonini aniqlash
 arr_randint.size

36

In [ ]:
# 3 o'lchamli array yaratish va kerakli qismini kesib olish
arr3d=np.array([[[12,45,12],
                 [24,45,1],
                 [78,66,4]],
                
                [[45,778,454],
                 [45,54565,4],
                 [45,45487,84545]],
                
                [[45,12,45],
                 [21,2456,54654],
                 [45,46,56]]])
arrsl=arr3d[2]
ss=arrsl[1:3,:2]
ss

array([[  21, 2456],
       [  45,   46]])

In [ ]:
# array yaratganda ularning ma'lumot turlarini berish (int16-64, float16-64,string,uint16_64)
arr3=np.array([21,245,21,5412,55])

In [ ]:
# arr3 ning ma'lumot turini tekshiramiz
arr3.dtype

dtype('int64')

In [ ]:
# arr3 ni float32 ga o'tkazamiz
arr3.astype(np.float32)


array([  21.,  245.,   21., 5412.,   55.], dtype=float32)

In [ ]:
#boolean indekslash
ismlar=np.array(["Halima","Jaxongir","Salim","Sunnat","Kamron","Baxrom"])
info=np.random.randn(6,3)


In [ ]:
print(ismlar)
print(info)


['Halima' 'Jaxongir' 'Salim' 'Sunnat' 'Kamron' 'Baxrom']
[[ 0.29564427  1.82258825  1.11053584]
 [-1.40817095  1.13279956  1.40500972]
 [ 0.3292685   0.20246705  0.80719134]
 [-1.90677334  1.96868009  1.16836254]
 [ 1.10213095  1.57867841 -0.68848261]
 [ 0.25560456  0.70692688  1.19954814]]


In [ ]:
# yuqorida ko'rib turgan ikki o'lchamli massivlarning har bir qatori har bir ismlarga tegishli

array([[0.29564427, 1.82258825, 1.11053584]])

In [ ]:
# Halimaning ma'lumotini chiqaramiz
info[ismlar=="Halima"]

array([[0.29564427, 1.82258825, 1.11053584]])

In [ ]:
ismlar=="Salim" # quyida ko'rishingiz mumkin 2 element True qiymatni qaytardi

array([False, False,  True, False, False, False])

In [ ]:
# info dagi manfiy sonlarni 0 ga ten qilish
info[info<0]=0

In [ ]:
info # quyida ko'rishingiz mumkin manfiy qiymatlar 0 ga teng bo'ldi

array([[0.29564427, 1.82258825, 1.11053584],
       [0.        , 1.13279956, 1.40500972],
       [0.3292685 , 0.20246705, 0.80719134],
       [0.        , 1.96868009, 1.16836254],
       [1.10213095, 1.57867841, 0.        ],
       [0.25560456, 0.70692688, 1.19954814]])

In [ ]:
# ismlardan ikkitasini ma'lumotini chiqarish
ism2=(ismlar=="Baxrom") | (ismlar=="Sunnat")
info[ism2]

array([[0.        , 1.96868009, 1.16836254],
       [0.25560456, 0.70692688, 1.19954814]])

In [ ]:
# unversal funksiyalar
# unary (bitta element qabul qiluvchi funksiyala)
haqiqiy_son=np.array([12.2,54.4,121.1,54.5,-0.15])
onlik,butun=np.modf(haqiqiy_son)

In [ ]:
onlik

array([ 0.2 ,  0.4 ,  0.1 ,  0.5 , -0.15])

In [ ]:
butun

array([ 12.,  54., 121.,  54.,  -0.])

In [ ]:
# yuqoridagi butun degan o'zgaruvchining oxirgi elementiga e'tibor bering. modf() funksiyasi  nuqtadan oldingi sonlarni ajratadi

In [ ]:
kvadrat_o=np.square(haqiqiy_son) 
kvadrat_o # square funksiyasi elementlarni kvadratga oshiradi

array([1.488400e+02, 2.959360e+03, 1.466521e+04, 2.970250e+03,
       2.250000e-02])

In [ ]:
# sqrt() kvadrat ildiz hisoblovchi funksiya
kvadrat_f=np.sqrt(haqiqiy_son)
kvadrat_f


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([ 3.49284984,  7.37563557, 11.00454452,  7.38241153,         nan])

In [ ]:
# isnan() funksiyasi  (Not a  Number)
isn_kv=np.isnan(kvadrat_f)
isn_kv

array([False, False, False, False,  True])

In [1]:
# rint metodi
import numpy as np
rand=np.random.rand(5)
rand

array([0.40466195, 0.92492213, 0.82501661, 0.77829752, 0.97160967])

In [3]:
np.rint(rand)

array([0., 1., 1., 1., 1.])

In [7]:
rand[1:4]=np.NaN

In [8]:
rand

array([0.40466195,        nan,        nan,        nan, 0.97160967])

In [11]:
# fmax funksiyasi
rand2=np.random.rand(5)
rand2

array([0.74945885, 0.99440275, 0.83204773, 0.70139309, 0.09121771])

In [14]:
np.fmax(rand,rand2)

array([0.74945885, 0.99440275, 0.83204773, 0.70139309, 0.97160967])

In [21]:
arr1=np.array([2,3,4])
arr1

array([2, 3, 4])

In [20]:
arr2=np.array([7,1,5])
arr2

array([7, 1, 5])

In [24]:
np.power(arr1,arr2) # power() birinchi arrayning elementlarini ikkinchi arrdagi elementlar darajasiga oshiradi

array([ 128,    3, 1024])

In [26]:
np.subtract(arr1,arr2) # subtract() birinchi arrayning elementlarini ikkinchi arrdagi elementlardan ayiradi 

array([-5,  2, -1])

In [29]:
np.multiply(arr1,arr2) # multiply birinchi arrayning elementlarini ikkinchi arrdagi elementlarga ko'paytiradi

array([14,  3, 20])

In [28]:
np.mod(arr1,arr2) # ?????

array([2, 0, 4])